import 'outfit_reference_data.dart';

/// Blue-focused outfit references. Each piece still resolves through the
/// ordinary clothing taxonomy, so users can apply a complete look and then
/// replace any garment, color, material, or detail independently.
const blueOutfitReferencePresets = <OutfitReferencePresetData>[
  OutfitReferencePresetData(
    id: 'blue_powder_lace_sundress',
    category: '藍色系列',
    name: '粉藍白蕾絲夏日洋裝',
    palette: '粉藍 × 白色',
    description: '輕柔粉藍棉質洋裝搭配白色蕾絲、蝴蝶結與涼鞋。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'sundress',
        mainColor: 'powder blue',
        secondaryColor: 'white',
        fit: 'fitted',
        length: 'above knee',
        materials: ['cotton'],
        details: ['lace trim', 'bow'],
        patterns: ['floral print'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'sandals',
        mainColor: 'white',
        secondaryColor: 'powder blue',
        materials: ['leather'],
      ),
    ],
    mainStyle: 'feminine',
    subStyle: 'romantic feminine style',
    mood: 'romantic mood',
    occasion: 'date outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_sky_blouse_pleated',
    category: '藍色系列',
    name: '天藍白襯衫百褶穿搭',
    palette: '天藍 × 白色',
    description: '白色合身女式襯衫、天藍百褶裙與同色系瑪莉珍鞋。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'blouse',
        mainColor: 'white',
        secondaryColor: 'sky blue',
        cut: 'above-elbow sleeves',
        fit: 'fitted',
        length: 'waist length',
        materials: ['cotton'],
        details: ['ribbon', 'piping'],
        patterns: ['solid color'],
      ),
      OutfitPiecePresetData(
        scope: 'skirt',
        garment: 'pleated skirt',
        mainColor: 'sky blue',
        secondaryColor: 'white',
        cut: 'high-waisted',
        fit: 'regular fit',
        length: 'knee length',
        materials: ['cotton'],
        details: ['pleats'],
      ),
      OutfitPiecePresetData(
        scope: 'socks',
        garment: 'kneehighs',
        mainColor: 'white',
        secondaryColor: 'sky blue',
        materials: ['cotton'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'mary janes',
        mainColor: 'white',
        secondaryColor: 'sky blue',
        materials: ['leather'],
      ),
    ],
    mainStyle: 'charming',
    subStyle: 'sweet feminine style',
    mood: 'cheerful mood',
    occasion: 'cafe outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_navy_silver_office',
    category: '藍色系列',
    name: '海軍藍銀邊辦公套裝',
    palette: '海軍藍 × 銀色 × 白色',
    description: '白襯衫搭配海軍藍西裝外套與長褲，以銀色滾邊收束。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'dress shirt',
        mainColor: 'white',
        secondaryColor: 'navy',
        cut: 'long sleeves',
        fit: 'tailored fit',
        length: 'waist length',
        materials: ['cotton'],
        details: ['buttons', 'piping'],
      ),
      OutfitPiecePresetData(
        scope: 'pants',
        garment: 'dress pants',
        mainColor: 'navy',
        secondaryColor: 'silver',
        cut: 'high-waisted',
        fit: 'tailored fit',
        length: 'ankle length',
        materials: ['wool'],
        details: ['pleats', 'piping'],
      ),
      OutfitPiecePresetData(
        scope: 'outerwear',
        garment: 'blazer',
        mainColor: 'navy',
        secondaryColor: 'silver',
        fit: 'tailored fit',
        length: 'hip length',
        materials: ['wool'],
        details: ['buttons', 'piping'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'pumps',
        mainColor: 'navy',
        secondaryColor: 'silver',
        materials: ['leather'],
      ),
    ],
    mainStyle: 'elegant',
    subStyle: 'classic elegant style',
    mood: 'formal mood',
    occasion: 'office outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_cobalt_gold_evening',
    category: '藍色系列',
    name: '鈷藍金邊單肩晚禮服',
    palette: '鈷藍 × 金色',
    description: '鈷藍緞面單肩晚禮服，搭配金色珠飾、高開衩與細高跟鞋。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'evening gown',
        mainColor: 'cobalt blue',
        secondaryColor: 'gold',
        cut: 'one-shoulder',
        fit: 'fitted',
        length: 'floor length',
        materials: ['satin'],
        details: ['beading', 'draped', 'high slit'],
        patterns: ['solid color'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'stiletto heels',
        mainColor: 'gold',
        secondaryColor: 'cobalt blue',
        materials: ['leather'],
      ),
    ],
    mainStyle: 'elegant',
    subStyle: 'glamorous sexy style',
    mood: 'luxurious mood',
    occasion: 'formal event outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_sapphire_silver_ball_gown',
    category: '藍色系列',
    name: '寶石藍銀色星光舞會禮服',
    palette: '寶石藍 × 銀色',
    description: '寶石藍露肩舞會禮服，加入銀色亮片與星紋層次。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'ball gown',
        mainColor: 'sapphire blue',
        secondaryColor: 'silver',
        cut: 'off-shoulder',
        fit: 'regular fit',
        length: 'floor length',
        materials: ['satin', 'organza'],
        details: ['sequins', 'layered'],
        patterns: ['star pattern'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'ankle strap heels',
        mainColor: 'silver',
        secondaryColor: 'sapphire blue',
        materials: ['leather'],
        details: ['rhinestones'],
      ),
    ],
    mainStyle: 'elegant',
    subStyle: 'princess fantasy style',
    mood: 'luxurious mood',
    occasion: 'party outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_aqua_white_resort',
    category: '藍色系列',
    name: '水藍白色渡假包裹洋裝',
    palette: '水藍 × 白色',
    description: '水藍雪紡包裹式洋裝配白色荷葉邊、腰帶與涼鞋。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'wrap dress',
        mainColor: 'aqua',
        secondaryColor: 'white',
        cut: 'halter neck',
        fit: 'relaxed fit',
        length: 'midi',
        materials: ['chiffon'],
        details: ['ruffles', 'belt'],
        patterns: ['leaf pattern'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'strappy sandals',
        mainColor: 'white',
        secondaryColor: 'aqua',
        materials: ['leather'],
        details: ['straps'],
      ),
      OutfitPiecePresetData(
        scope: 'accessory',
        garment: 'hat',
        mainColor: 'white',
        secondaryColor: 'aqua',
        materials: ['cotton'],
        details: ['ribbon'],
      ),
    ],
    mainStyle: 'feminine',
    subStyle: 'relaxed casual style',
    mood: 'cheerful mood',
    occasion: 'travel outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_teal_black_jumpsuit',
    category: '藍色系列',
    name: '藍綠黑色俐落連身褲',
    palette: '藍綠 × 黑色',
    description: '藍綠色合身連身褲，以黑色腰帶、拉鍊與滾邊塑造俐落輪廓。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'jumpsuit',
        mainColor: 'teal',
        secondaryColor: 'black',
        cut: 'high-waisted',
        fit: 'tailored fit',
        length: 'ankle length',
        materials: ['satin'],
        details: ['belt', 'zipper', 'piping'],
        patterns: ['color block'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'ankle boots',
        mainColor: 'black',
        secondaryColor: 'teal',
        materials: ['leather'],
        details: ['zipper'],
      ),
    ],
    mainStyle: 'minimalist',
    subStyle: 'modern minimal style',
    mood: 'cool mood',
    occasion: 'party outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_royal_white_cocktail',
    category: '藍色系列',
    name: '寶藍白結雞尾酒洋裝',
    palette: '寶藍 × 白色',
    description: '寶藍絲質單肩雞尾酒洋裝，以白色蝴蝶結和抓皺增加層次。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'cocktail dress',
        mainColor: 'royal blue',
        secondaryColor: 'white',
        cut: 'one-shoulder',
        fit: 'tailored fit',
        length: 'knee length',
        materials: ['silk'],
        details: ['bow', 'ruched'],
        patterns: ['solid color'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'pumps',
        mainColor: 'white',
        secondaryColor: 'royal blue',
        materials: ['leather'],
      ),
    ],
    mainStyle: 'elegant',
    subStyle: 'classic elegant style',
    mood: 'formal mood',
    occasion: 'wedding guest outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_light_cream_cafe',
    category: '藍色系列',
    name: '淺藍奶油針織咖啡穿搭',
    palette: '淺藍 × 奶油色',
    description: '淺藍針織上衣搭配奶油色中長 A 字裙和樂福鞋。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'knit top',
        mainColor: 'light blue',
        secondaryColor: 'cream',
        cut: 'crew neck',
        fit: 'regular fit',
        length: 'waist length',
        materials: ['knit'],
        details: ['buttons'],
      ),
      OutfitPiecePresetData(
        scope: 'skirt',
        garment: 'a-line skirt',
        mainColor: 'cream',
        secondaryColor: 'light blue',
        cut: 'natural waist',
        fit: 'regular fit',
        length: 'midi',
        materials: ['wool'],
        details: ['pleats'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'loafers',
        mainColor: 'brown',
        secondaryColor: 'light blue',
        materials: ['leather'],
      ),
    ],
    mainStyle: 'casual',
    subStyle: 'smart casual style',
    mood: 'sweet mood',
    occasion: 'cafe outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_dark_steel_travel',
    category: '藍色系列',
    name: '深藍鋼藍風衣旅行穿搭',
    palette: '深藍 × 鋼藍 × 灰色',
    description: '灰藍上衣與深藍直筒褲，外搭鋼藍及膝風衣。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 't-shirt',
        mainColor: 'gray',
        secondaryColor: 'dark blue',
        cut: 'crew neck',
        fit: 'regular fit',
        length: 'waist length',
        materials: ['cotton'],
        details: ['piping'],
        patterns: ['solid color'],
      ),
      OutfitPiecePresetData(
        scope: 'pants',
        garment: 'straight-leg pants',
        mainColor: 'dark blue',
        secondaryColor: 'gray',
        cut: 'natural waist',
        fit: 'regular fit',
        length: 'full length',
        materials: ['cotton'],
        details: ['belt'],
      ),
      OutfitPiecePresetData(
        scope: 'outerwear',
        garment: 'trench coat',
        mainColor: 'steel blue',
        secondaryColor: 'dark blue',
        fit: 'regular fit',
        length: 'knee length',
        materials: ['cotton'],
        details: ['buttons', 'belt'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'ankle boots',
        mainColor: 'dark blue',
        secondaryColor: 'gray',
        materials: ['leather'],
      ),
    ],
    mainStyle: 'casual',
    subStyle: 'smart casual style',
    mood: 'cool mood',
    occasion: 'travel outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_denim_white_casual',
    category: '藍色系列',
    name: '丹寧藍白休閒層次穿搭',
    palette: '丹寧藍 × 白色',
    description: '白色細肩帶上衣、藍色牛仔褲與牛仔外套組成清爽層次。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'camisole',
        mainColor: 'white',
        secondaryColor: 'blue',
        cut: 'sleeveless',
        fit: 'fitted',
        length: 'waist length',
        materials: ['cotton'],
        details: ['lace trim'],
      ),
      OutfitPiecePresetData(
        scope: 'pants',
        garment: 'jeans',
        mainColor: 'blue',
        secondaryColor: 'white',
        cut: 'natural waist',
        fit: 'regular fit',
        length: 'ankle length',
        materials: ['denim'],
        details: ['belt'],
      ),
      OutfitPiecePresetData(
        scope: 'outerwear',
        garment: 'denim jacket',
        mainColor: 'blue',
        secondaryColor: 'white',
        fit: 'regular fit',
        length: 'hip length',
        materials: ['denim'],
        details: ['buttons'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'sneakers',
        mainColor: 'white',
        secondaryColor: 'blue',
        materials: ['mesh'],
        details: ['lace-up'],
      ),
    ],
    mainStyle: 'casual',
    subStyle: 'relaxed casual style',
    mood: 'cheerful mood',
    occasion: 'casual outing outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_navy_aqua_tracksuit',
    category: '藍色系列',
    name: '海軍藍水藍運動套裝',
    palette: '海軍藍 × 水藍 × 白色',
    description: '海軍藍運動上衣和慢跑褲，以水藍滾邊搭配白色跑鞋。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'sweatshirt',
        mainColor: 'navy',
        secondaryColor: 'aqua',
        cut: 'crew neck',
        fit: 'relaxed fit',
        length: 'hip length',
        materials: ['cotton'],
        details: ['piping'],
      ),
      OutfitPiecePresetData(
        scope: 'pants',
        garment: 'joggers',
        mainColor: 'navy',
        secondaryColor: 'aqua',
        cut: 'natural waist',
        fit: 'regular fit',
        length: 'full length',
        materials: ['cotton'],
        details: ['piping'],
      ),
      OutfitPiecePresetData(
        scope: 'outerwear',
        garment: 'track jacket',
        mainColor: 'navy',
        secondaryColor: 'aqua',
        fit: 'regular fit',
        length: 'hip length',
        materials: ['cotton'],
        details: ['zipper', 'piping'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'running shoes',
        mainColor: 'white',
        secondaryColor: 'navy',
        materials: ['mesh'],
        details: ['lace-up'],
      ),
    ],
    mainStyle: 'sportswear',
    subStyle: 'athleisure style',
    mood: 'sporty mood',
    occasion: 'gym outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_sky_pink_tennis',
    category: '藍色系列',
    name: '天藍粉紅網球穿搭',
    palette: '天藍 × 淺粉紅 × 白色',
    description: '白色運動上衣、天藍運動裙與淺粉紅細節組成明快配色。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 't-shirt',
        mainColor: 'white',
        secondaryColor: 'sky blue',
        cut: 'crew neck',
        fit: 'fitted',
        length: 'waist length',
        materials: ['cotton'],
        details: ['piping'],
      ),
      OutfitPiecePresetData(
        scope: 'skirt',
        garment: 'sports skirt',
        mainColor: 'sky blue',
        secondaryColor: 'light pink',
        cut: 'high-waisted',
        fit: 'regular fit',
        length: 'above knee',
        materials: ['cotton'],
        details: ['pleats'],
      ),
      OutfitPiecePresetData(
        scope: 'socks',
        garment: 'socks',
        mainColor: 'white',
        secondaryColor: 'sky blue',
        materials: ['cotton'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'tennis shoes',
        mainColor: 'white',
        secondaryColor: 'light pink',
        materials: ['mesh'],
        details: ['lace-up'],
      ),
    ],
    mainStyle: 'sportswear',
    subStyle: 'athleisure style',
    mood: 'playful mood',
    occasion: 'sports outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_cobalt_orange_basketball',
    category: '藍色系列',
    name: '鈷藍橘邊籃球穿搭',
    palette: '鈷藍 × 橘色 × 白色',
    description: '鈷藍籃球球衣和運動短褲搭配橘色滾邊與白藍球鞋。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'basketball jersey',
        mainColor: 'cobalt blue',
        secondaryColor: 'orange',
        cut: 'sleeveless',
        fit: 'loose fit',
        length: 'hip length',
        materials: ['mesh'],
        details: ['piping'],
      ),
      OutfitPiecePresetData(
        scope: 'shorts',
        garment: 'sports shorts',
        mainColor: 'cobalt blue',
        secondaryColor: 'orange',
        cut: 'natural waist',
        fit: 'regular fit',
        length: 'upper-thigh length',
        materials: ['mesh'],
        details: ['piping'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'basketball shoes',
        mainColor: 'white',
        secondaryColor: 'cobalt blue',
        materials: ['mesh'],
        details: ['lace-up'],
      ),
    ],
    mainStyle: 'sportswear',
    subStyle: 'athleisure style',
    mood: 'sporty mood',
    occasion: 'sports outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_aqua_navy_running',
    category: '藍色系列',
    name: '水藍海軍藍跑步穿搭',
    palette: '水藍 × 海軍藍 × 白色',
    description: '水藍削肩背心搭配海軍藍自行車短褲與同色系跑鞋。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'tank top',
        mainColor: 'aqua',
        secondaryColor: 'navy',
        cut: 'racerback',
        fit: 'fitted',
        length: 'waist length',
        materials: ['mesh'],
        details: ['piping'],
      ),
      OutfitPiecePresetData(
        scope: 'shorts',
        garment: 'bike shorts',
        mainColor: 'navy',
        secondaryColor: 'aqua',
        cut: 'high-waisted',
        fit: 'fitted',
        length: 'upper-thigh length',
        materials: ['mesh'],
        details: ['piping'],
      ),
      OutfitPiecePresetData(
        scope: 'socks',
        garment: 'socks',
        mainColor: 'white',
        secondaryColor: 'aqua',
        materials: ['cotton'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'running shoes',
        mainColor: 'navy',
        secondaryColor: 'aqua',
        materials: ['mesh'],
        details: ['lace-up'],
      ),
    ],
    mainStyle: 'sportswear',
    subStyle: 'athleisure style',
    mood: 'sporty mood',
    occasion: 'outdoor outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_steel_black_techwear',
    category: '藍色系列',
    name: '鋼藍黑色機能街頭穿搭',
    palette: '鋼藍 × 黑色',
    description: '鋼藍連帽上衣與飛行夾克搭配黑色工裝褲和戰鬥靴。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'hoodie',
        mainColor: 'steel blue',
        secondaryColor: 'black',
        fit: 'oversized',
        length: 'hip length',
        materials: ['cotton'],
        details: ['zipper', 'straps'],
      ),
      OutfitPiecePresetData(
        scope: 'pants',
        garment: 'cargo pants',
        mainColor: 'black',
        secondaryColor: 'steel blue',
        cut: 'high-waisted',
        fit: 'loose fit',
        length: 'full length',
        materials: ['cotton'],
        details: ['buckles', 'straps', 'piping'],
      ),
      OutfitPiecePresetData(
        scope: 'outerwear',
        garment: 'bomber jacket',
        mainColor: 'steel blue',
        secondaryColor: 'black',
        fit: 'loose fit',
        length: 'hip length',
        materials: ['leather'],
        details: ['zipper', 'buckles'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'combat boots',
        mainColor: 'black',
        secondaryColor: 'steel blue',
        materials: ['leather'],
        details: ['lace-up'],
      ),
    ],
    mainStyle: 'streetwear',
    subStyle: 'techwear style',
    mood: 'tough mood',
    occasion: 'casual outing outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_turquoise_white_resort',
    category: '藍色系列',
    name: '土耳其藍白色襯衫裙',
    palette: '土耳其藍 × 白色',
    description: '土耳其藍亞麻襯衫裙搭配白色條紋、腰帶與輕便涼鞋。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'shirt dress',
        mainColor: 'turquoise',
        secondaryColor: 'white',
        cut: 'natural waist',
        fit: 'relaxed fit',
        length: 'midi',
        materials: ['linen'],
        details: ['buttons', 'belt'],
        patterns: ['striped'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'sandals',
        mainColor: 'white',
        secondaryColor: 'turquoise',
        materials: ['leather'],
        details: ['straps'],
      ),
      OutfitPiecePresetData(
        scope: 'accessory',
        garment: 'hat',
        mainColor: 'white',
        secondaryColor: 'turquoise',
        materials: ['cotton'],
        details: ['ribbon'],
      ),
    ],
    mainStyle: 'casual',
    subStyle: 'relaxed casual style',
    mood: 'cheerful mood',
    occasion: 'beach outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_pastel_lavender_tiered',
    category: '藍色系列',
    name: '粉彩藍淡紫蛋糕洋裝',
    palette: '粉彩藍 × 淡紫色 × 白色',
    description: '粉彩藍雪紡洋裝加入淡紫荷葉邊、白色蕾絲與圓點。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'dress',
        mainColor: 'pastel blue',
        secondaryColor: 'lavender',
        cut: 'off-shoulder',
        fit: 'fitted',
        length: 'above knee',
        materials: ['chiffon'],
        details: ['ruffles', 'lace trim', 'bow', 'layered'],
        patterns: ['polka dot'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'mary janes',
        mainColor: 'white',
        secondaryColor: 'lavender',
        materials: ['leather'],
        details: ['bow'],
      ),
    ],
    mainStyle: 'charming',
    subStyle: 'sweet feminine style',
    mood: 'sweet mood',
    occasion: 'date outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_midnight_purple_witch',
    category: '藍色系列',
    name: '午夜藍紫色星紋女巫裝',
    palette: '午夜藍 × 紫色 × 銀色',
    description: '午夜藍天鵝絨長洋裝搭配紫色蕾絲、銀色星紋與女巫帽。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'dress',
        mainColor: 'midnight blue',
        secondaryColor: 'purple',
        fit: 'fitted',
        length: 'floor length',
        materials: ['velvet', 'lace'],
        details: ['lace trim', 'layered'],
        patterns: ['star pattern'],
      ),
      OutfitPiecePresetData(
        scope: 'accessory',
        garment: 'hat',
        mainColor: 'midnight blue',
        secondaryColor: 'purple',
        materials: ['velvet'],
        details: ['ribbon'],
        patterns: ['star pattern'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'lace-up boots',
        mainColor: 'black',
        secondaryColor: 'purple',
        materials: ['leather'],
        details: ['lace-up'],
      ),
    ],
    mainStyle: 'fantasy',
    subStyle: 'witch fantasy style',
    mood: 'mysterious mood',
    occasion: 'party outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_navy_gold_military',
    category: '藍色系列',
    name: '海軍藍金邊軍裝套裝',
    palette: '海軍藍 × 金色 × 黑色',
    description: '海軍藍軍服以金色鈕扣、腰帶與滾邊搭配黑色及膝靴。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'costume',
        garment: 'military uniform',
        mainColor: 'navy',
        secondaryColor: 'gold',
        materials: ['wool'],
        details: ['buttons', 'belt', 'buckles', 'piping'],
        patterns: ['solid color'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'knee boots',
        mainColor: 'black',
        secondaryColor: 'gold',
        materials: ['leather'],
        details: ['buckles'],
      ),
      OutfitPiecePresetData(
        scope: 'accessory',
        garment: 'gloves',
        mainColor: 'white',
        secondaryColor: 'gold',
        materials: ['leather'],
      ),
    ],
    mainStyle: 'vintage',
    subStyle: 'classic elegant style',
    mood: 'formal mood',
    occasion: 'formal event outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_white_kimono',
    category: '藍色系列',
    name: '藍白櫻花絲質和服',
    palette: '藍色 × 白色 × 粉紅色',
    description: '藍色絲質和服搭配白色腰帶、粉紅櫻花印花與草履。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'costume',
        garment: 'kimono',
        mainColor: 'blue',
        secondaryColor: 'white',
        materials: ['silk'],
        details: ['belt', 'floral embroidery'],
        patterns: ['cherry blossom print'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'zouri',
        mainColor: 'white',
        secondaryColor: 'blue',
      ),
      OutfitPiecePresetData(
        scope: 'accessory',
        garment: 'hair ornament',
        mainColor: 'pink',
        secondaryColor: 'blue',
        materials: ['silk'],
        details: ['embroidery'],
      ),
    ],
    mainStyle: 'elegant',
    subStyle: 'classic elegant style',
    mood: 'elegant mood',
    occasion: 'formal event outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_aqua_white_yukata',
    category: '藍色系列',
    name: '水藍白葉紋浴衣',
    palette: '水藍 × 白色 × 棕色',
    description: '水藍棉質浴衣搭配白色腰帶、葉片圖案與棕色木屐。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'costume',
        garment: 'yukata',
        mainColor: 'aqua',
        secondaryColor: 'white',
        materials: ['cotton'],
        details: ['belt'],
        patterns: ['leaf pattern'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'geta',
        mainColor: 'brown',
        secondaryColor: 'aqua',
      ),
      OutfitPiecePresetData(
        scope: 'accessory',
        garment: 'hair ribbon',
        mainColor: 'white',
        secondaryColor: 'aqua',
        materials: ['silk'],
      ),
    ],
    mainStyle: 'feminine',
    subStyle: 'romantic feminine style',
    mood: 'cheerful mood',
    occasion: 'casual outing outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_dark_silver_ninja',
    category: '藍色系列',
    name: '深藍銀邊女忍者套裝',
    palette: '深藍 × 銀色 × 黑色',
    description: '深藍忍者套裝搭配銀色滾邊、黑色分趾靴與手套。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'costume',
        garment: 'ninja outfit',
        mainColor: 'dark blue',
        secondaryColor: 'silver',
        materials: ['cotton', 'mesh'],
        details: ['belt', 'straps', 'piping'],
        patterns: ['solid color'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'tabi boots',
        mainColor: 'black',
        secondaryColor: 'dark blue',
        materials: ['leather'],
        details: ['lace-up'],
      ),
      OutfitPiecePresetData(
        scope: 'accessory',
        garment: 'gloves',
        mainColor: 'dark blue',
        secondaryColor: 'silver',
        materials: ['leather'],
        details: ['straps'],
      ),
    ],
    mainStyle: 'fantasy',
    subStyle: 'techwear style',
    mood: 'tough mood',
    occasion: 'outdoor outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_royal_black_maid',
    category: '藍色系列',
    name: '寶藍黑蕾絲女僕裝',
    palette: '寶藍 × 黑色 × 白色',
    description: '寶藍女僕裝搭配黑色蕾絲、白色荷葉邊與厚底鞋。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'costume',
        garment: 'maid',
        mainColor: 'royal blue',
        secondaryColor: 'black',
        materials: ['cotton', 'lace'],
        details: ['ruffles', 'frills', 'lace trim', 'bow'],
        patterns: ['solid color'],
      ),
      OutfitPiecePresetData(
        scope: 'socks',
        garment: 'thighhighs',
        mainColor: 'white',
        secondaryColor: 'royal blue',
        materials: ['cotton'],
        details: ['bow'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'platform shoes',
        mainColor: 'black',
        secondaryColor: 'royal blue',
        materials: ['leather'],
        details: ['straps'],
      ),
    ],
    mainStyle: 'goth fashion',
    subStyle: 'romantic gothic style',
    mood: 'playful mood',
    occasion: 'party outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_powder_ivory_guest',
    category: '藍色系列',
    name: '粉藍象牙白花卉宴會洋裝',
    palette: '粉藍 × 象牙白',
    description: '粉藍歐根紗單肩洋裝搭配象牙白花卉刺繡與珍珠。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'dress',
        mainColor: 'powder blue',
        secondaryColor: 'ivory',
        cut: 'one-shoulder',
        fit: 'tailored fit',
        length: 'midi',
        materials: ['organza'],
        details: ['floral embroidery', 'pearls'],
        patterns: ['floral print'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'ankle strap heels',
        mainColor: 'ivory',
        secondaryColor: 'powder blue',
        materials: ['leather'],
        details: ['pearls'],
      ),
    ],
    mainStyle: 'elegant',
    subStyle: 'romantic feminine style',
    mood: 'romantic mood',
    occasion: 'wedding guest outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_sapphire_rose_gold_gown',
    category: '藍色系列',
    name: '寶石藍玫瑰金華麗禮服',
    palette: '寶石藍 × 玫瑰金',
    description: '寶石藍天鵝絨露肩禮服，以玫瑰金珠飾與抓皺呈現華麗感。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'evening gown',
        mainColor: 'sapphire blue',
        secondaryColor: 'rose gold',
        cut: 'off-shoulder',
        fit: 'fitted',
        length: 'floor length',
        materials: ['velvet'],
        details: ['high slit', 'beading', 'ruched'],
        patterns: ['solid color'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'stiletto heels',
        mainColor: 'rose gold',
        secondaryColor: 'sapphire blue',
        materials: ['leather'],
        details: ['rhinestones'],
      ),
    ],
    mainStyle: 'elegant',
    subStyle: 'glamorous sexy style',
    mood: 'luxurious mood',
    occasion: 'formal event outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_teal_cream_bohemian',
    category: '藍色系列',
    name: '藍綠奶油波希米亞長洋裝',
    palette: '藍綠 × 奶油色 × 棕色',
    description: '藍綠雪紡長洋裝搭配奶油色層次、花卉圖案與棕色涼鞋。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'wrap dress',
        mainColor: 'teal',
        secondaryColor: 'cream',
        cut: 'halter neck',
        fit: 'relaxed fit',
        length: 'maxi',
        materials: ['chiffon'],
        details: ['layered', 'belt'],
        patterns: ['floral print'],
      ),
      OutfitPiecePresetData(
        scope: 'outerwear',
        garment: 'shawl',
        mainColor: 'cream',
        secondaryColor: 'teal',
        fit: 'relaxed fit',
        length: 'hip length',
        materials: ['knit'],
        details: ['embroidery'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'strappy sandals',
        mainColor: 'brown',
        secondaryColor: 'teal',
        materials: ['suede'],
        details: ['straps'],
      ),
    ],
    mainStyle: 'bohemian',
    subStyle: 'romantic feminine style',
    mood: 'romantic mood',
    occasion: 'travel outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_steel_burgundy_vintage',
    category: '藍色系列',
    name: '鋼藍酒紅復古西裝套裝',
    palette: '鋼藍 × 酒紅色 × 棕色',
    description: '鋼藍羊毛正式外套套裝搭配酒紅格紋、滾邊與棕色牛津鞋。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'costume',
        garment: 'formal blazer outfit',
        mainColor: 'steel blue',
        secondaryColor: 'burgundy',
        materials: ['wool'],
        details: ['pleats', 'buttons', 'piping'],
        patterns: ['plaid'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'oxfords',
        mainColor: 'brown',
        secondaryColor: 'steel blue',
        materials: ['leather'],
        details: ['lace-up'],
      ),
      OutfitPiecePresetData(
        scope: 'accessory',
        garment: 'necktie',
        mainColor: 'burgundy',
        secondaryColor: 'steel blue',
        materials: ['silk'],
        patterns: ['striped'],
      ),
    ],
    mainStyle: 'vintage',
    subStyle: 'classic elegant style',
    mood: 'mature mood',
    occasion: 'business casual outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_silver_futuristic',
    category: '藍色系列',
    name: '藍銀未來感連身褲',
    palette: '藍色 × 銀色',
    description: '藍色乳膠合身連身褲，以銀色拼接、鏤空與踝靴呈現未來感。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'jumpsuit',
        mainColor: 'blue',
        secondaryColor: 'silver',
        cut: 'high-waisted',
        fit: 'fitted',
        length: 'ankle length',
        materials: ['latex'],
        details: ['zipper', 'cutout'],
        patterns: ['color block'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'ankle boots',
        mainColor: 'silver',
        secondaryColor: 'blue',
        materials: ['latex'],
        details: ['zipper'],
      ),
      OutfitPiecePresetData(
        scope: 'accessory',
        garment: 'gloves',
        mainColor: 'silver',
        secondaryColor: 'blue',
        materials: ['latex'],
        details: ['straps'],
      ),
    ],
    mainStyle: 'futuristic',
    subStyle: 'cyberpunk style',
    mood: 'cool mood',
    occasion: 'party outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_navy_white_kyudo',
    category: '藍色系列',
    name: '海軍藍白色弓道服',
    palette: '海軍藍 × 白色 × 棕色',
    description: '海軍藍弓道服搭配白色百褶、分趾襪與棕色草履。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'costume',
        garment: 'kyudo uniform',
        mainColor: 'navy',
        secondaryColor: 'white',
        materials: ['cotton'],
        details: ['pleats', 'belt'],
        patterns: ['solid color'],
      ),
      OutfitPiecePresetData(
        scope: 'socks',
        garment: 'tabi',
        mainColor: 'white',
        secondaryColor: 'navy',
        materials: ['cotton'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'zouri',
        mainColor: 'brown',
        secondaryColor: 'navy',
      ),
    ],
    mainStyle: 'elegant',
    subStyle: 'classic elegant style',
    mood: 'formal mood',
    occasion: 'sports outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_azure_white_minimal',
    category: '藍色系列',
    name: '蔚藍白色極簡長褲穿搭',
    palette: '蔚藍 × 白色 × 銀色',
    description: '蔚藍無袖上衣搭配白色寬褲，以銀色細節保持俐落清爽。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'tank top',
        mainColor: 'azure',
        secondaryColor: 'white',
        cut: 'sleeveless',
        fit: 'fitted',
        length: 'waist length',
        materials: ['silk'],
        details: ['piping'],
        patterns: ['solid color'],
      ),
      OutfitPiecePresetData(
        scope: 'pants',
        garment: 'wide-leg pants',
        mainColor: 'white',
        secondaryColor: 'azure',
        cut: 'high-waisted',
        fit: 'relaxed fit',
        length: 'full length',
        materials: ['linen'],
        details: ['belt', 'piping'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'flats',
        mainColor: 'silver',
        secondaryColor: 'azure',
        materials: ['leather'],
      ),
    ],
    mainStyle: 'minimalist',
    subStyle: 'modern minimal style',
    mood: 'elegant mood',
    occasion: 'daily outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_cobalt_white_sailor',
    category: '藍色系列',
    name: '鈷藍白色水手風套裝',
    palette: '鈷藍 × 白色 × 紅色',
    description: '鈷藍水手風套裝搭配白色百褶與紅色領結，呈現鮮明配色。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'costume',
        garment: 'sailor-style outfit',
        mainColor: 'cobalt blue',
        secondaryColor: 'white',
        materials: ['cotton'],
        details: ['pleats', 'ribbon', 'piping'],
        patterns: ['solid color'],
      ),
      OutfitPiecePresetData(
        scope: 'accessory',
        garment: 'neck ribbon',
        mainColor: 'red',
        secondaryColor: 'cobalt blue',
        materials: ['silk'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'loafers',
        mainColor: 'brown',
        secondaryColor: 'cobalt blue',
        materials: ['leather'],
      ),
    ],
    mainStyle: 'preppy',
    subStyle: 'classic elegant style',
    mood: 'cheerful mood',
    occasion: 'daytime formal outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_midnight_red_gothic',
    category: '藍色系列',
    name: '午夜藍深紅哥德晚禮服',
    palette: '午夜藍 × 深紅色 × 黑色',
    description: '午夜藍天鵝絨禮服以深紅蕾絲、荷葉邊與黑色厚底高跟鞋搭配。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'evening gown',
        mainColor: 'midnight blue',
        secondaryColor: 'dark red',
        fit: 'fitted',
        length: 'floor length',
        materials: ['velvet', 'lace'],
        details: ['lace trim', 'ruffles', 'corset lacing'],
        patterns: ['rose print'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'platform heels',
        mainColor: 'black',
        secondaryColor: 'dark red',
        materials: ['leather'],
        details: ['straps'],
      ),
      OutfitPiecePresetData(
        scope: 'accessory',
        garment: 'choker',
        mainColor: 'dark red',
        secondaryColor: 'midnight blue',
        materials: ['velvet'],
        details: ['lace trim'],
      ),
    ],
    mainStyle: 'goth fashion',
    subStyle: 'Victorian gothic style',
    mood: 'mysterious mood',
    occasion: 'party outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_sky_white_ballet',
    category: '藍色系列',
    name: '天藍白色芭蕾風穿搭',
    palette: '天藍 × 白色 × 銀色',
    description: '天藍合身上衣搭配白色薄紗芭蕾舞裙與銀色足尖鞋。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'tank top',
        mainColor: 'sky blue',
        secondaryColor: 'white',
        cut: 'sleeveless',
        fit: 'fitted',
        length: 'waist length',
        materials: ['cotton'],
        details: ['ribbon'],
      ),
      OutfitPiecePresetData(
        scope: 'skirt',
        garment: 'tutu',
        mainColor: 'white',
        secondaryColor: 'sky blue',
        cut: 'natural waist',
        fit: 'regular fit',
        length: 'above knee',
        materials: ['tulle'],
        details: ['layered', 'ribbon'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'pointe shoes',
        mainColor: 'silver',
        secondaryColor: 'sky blue',
        details: ['ribbon'],
      ),
    ],
    mainStyle: 'feminine',
    subStyle: 'classic elegant style',
    mood: 'elegant mood',
    occasion: 'formal event outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_powder_gray_homewear',
    category: '藍色系列',
    name: '粉藍灰色柔軟居家穿搭',
    palette: '粉藍 × 淺灰 × 白色',
    description: '粉藍寬鬆針織上衣搭配淺灰慢跑褲與白色室內拖鞋。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'sweater',
        mainColor: 'powder blue',
        secondaryColor: 'white',
        cut: 'boat neck',
        fit: 'oversized',
        length: 'hip length',
        materials: ['ribbed knit'],
      ),
      OutfitPiecePresetData(
        scope: 'pants',
        garment: 'joggers',
        mainColor: 'light gray',
        secondaryColor: 'powder blue',
        cut: 'natural waist',
        fit: 'relaxed fit',
        length: 'full length',
        materials: ['cotton'],
        details: ['piping'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'house slippers',
        mainColor: 'white',
        secondaryColor: 'powder blue',
      ),
    ],
    mainStyle: 'casual',
    subStyle: 'relaxed casual style',
    mood: 'sweet mood',
    occasion: 'homewear outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_teal_black_leather',
    category: '藍色系列',
    name: '藍綠黑色皮革街頭穿搭',
    palette: '藍綠 × 黑色 × 銀色',
    description: '藍綠上衣、黑色皮褲與皮夾克搭配銀色拉鍊和扣環。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'crop top',
        mainColor: 'teal',
        secondaryColor: 'black',
        cut: 'sleeveless',
        fit: 'fitted',
        length: 'cropped',
        materials: ['cotton'],
        details: ['straps'],
      ),
      OutfitPiecePresetData(
        scope: 'pants',
        garment: 'leather pants',
        mainColor: 'black',
        secondaryColor: 'teal',
        cut: 'high-waisted',
        fit: 'fitted',
        length: 'full length',
        materials: ['leather'],
        details: ['zipper', 'buckles'],
      ),
      OutfitPiecePresetData(
        scope: 'outerwear',
        garment: 'leather jacket',
        mainColor: 'black',
        secondaryColor: 'teal',
        fit: 'tailored fit',
        length: 'hip length',
        materials: ['leather'],
        details: ['zipper', 'buckles', 'chains'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'platform boots',
        mainColor: 'black',
        secondaryColor: 'teal',
        materials: ['leather'],
        details: ['buckles'],
      ),
    ],
    mainStyle: 'streetwear',
    subStyle: 'urban streetwear style',
    mood: 'cool mood',
    occasion: 'casual outing outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_royal_gold_princess',
    category: '藍色系列',
    name: '寶藍金色公主舞會禮服',
    palette: '寶藍 × 金色 × 白色',
    description: '寶藍舞會禮服搭配金色刺繡、珍珠與白色薄紗多層裙襬。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'ball gown',
        mainColor: 'royal blue',
        secondaryColor: 'gold',
        cut: 'off-shoulder',
        fit: 'fitted',
        length: 'floor length',
        materials: ['satin', 'tulle'],
        details: ['embroidery', 'pearls', 'layered'],
        patterns: ['solid color'],
      ),
      OutfitPiecePresetData(
        scope: 'accessory',
        garment: 'tiara',
        mainColor: 'gold',
        secondaryColor: 'royal blue',
        details: ['rhinestones', 'pearls'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'pumps',
        mainColor: 'white',
        secondaryColor: 'gold',
        materials: ['leather'],
        details: ['rhinestones'],
      ),
    ],
    mainStyle: 'fantasy',
    subStyle: 'princess fantasy style',
    mood: 'luxurious mood',
    occasion: 'formal event outfit',
  ),
  OutfitReferencePresetData(
    id: 'blue_indigo_white_layered',
    category: '藍色系列',
    name: '深藍白色分層裙裝',
    palette: '深藍 × 白色 × 淺藍',
    description: '淺藍合身翻領排扣襯衫，搭配白色荷葉與蕾絲前襟、深藍領結及白色分層中長裙。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'accessory',
        garment: 'large hair bow',
        mainColor: 'dark blue',
      ),
      OutfitPiecePresetData(
        scope: 'accessory',
        garment: 'neck ribbon',
        mainColor: 'dark blue',
      ),
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'collared blouse',
        mainColor: 'light blue',
        secondaryColor: 'white',
        cut: 'long sleeves',
        fit: 'fitted',
        length: 'waist length',
        materials: ['cotton'],
        details: ['buttons', 'lace trim', 'ruffles'],
        detailColor: 'white',
      ),
      OutfitPiecePresetData(
        scope: 'accessory',
        garment: 'belt',
        mainColor: 'dark blue',
      ),
      OutfitPiecePresetData(
        scope: 'skirt',
        garment: 'tiered skirt',
        mainColor: 'white',
        secondaryColor: 'light blue',
        cut: 'high-waisted',
        fit: 'regular fit',
        length: 'midi',
        materials: ['chiffon'],
        details: ['layered', 'ribbon'],
        patterns: ['solid color'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'ankle boots',
        mainColor: 'dark blue',
        secondaryColor: 'light blue',
        materials: ['suede'],
        details: ['lace-up'],
      ),
    ],
    mainStyle: 'feminine',
    subStyle: 'romantic feminine style',
    mood: 'romantic mood',
    occasion: 'date outfit',
  ),
];
