import 'catalog_data.dart';

String _clothingSlug(String value) => value
    .toLowerCase()
    .replaceAll(RegExp(r'[^a-z0-9]+'), '_')
    .replaceAll(RegExp(r'^_+|_+$'), '');

CatalogTagData _clothingTag({
  required String id,
  required String group,
  required String zh,
  required String en,
  String? conflictGroup,
  String support = 'official',
  bool adult = false,
}) =>
    CatalogTagData(
      id: id,
      group: group,
      zh: zh,
      en: en,
      order: 2,
      conflictGroup: conflictGroup,
      support: support,
      adult: adult,
    );

List<CatalogTagData> _garments(
  String group,
  String scope,
  List<(String, String)> values, {
  String support = 'official',
  bool adult = false,
}) =>
    values
        .map(
          (value) => _clothingTag(
            id: 'taxonomy_${scope}_${_clothingSlug(value.$2)}',
            group: group,
            zh: value.$1,
            en: value.$2,
            conflictGroup: _garmentConflictGroup(scope, value.$2),
            support: support,
            adult: adult,
          ),
        )
        .toList();

List<CatalogTagData> _dimensions(
  String scope,
  String dimension,
  List<(String, String)> values, {
  String? support,
}) =>
    values
        .map(
          (value) => _clothingTag(
            id: 'taxonomy_${scope}_${dimension}_${_clothingSlug(value.$2)}',
            group: 'clothing_scope_${scope}_$dimension',
            zh: value.$1,
            en: value.$2,
            conflictGroup: '${scope}_$dimension',
            support: support ?? _clothingDimensionSupport(dimension, value.$2),
          ),
        )
        .toList();

List<CatalogTagData> _overall(
  String idPrefix,
  String group,
  List<(String, String)> values,
) =>
    values
        .map(
          (value) => _clothingTag(
            id: '${idPrefix}_${_clothingSlug(value.$2)}',
            group: group,
            zh: value.$1,
            en: value.$2,
            conflictGroup: idPrefix,
            support: 'description',
          ),
        )
        .toList();

String _garmentConflictGroup(String scope, String english) => switch (scope) {
      'top' => 'top',
      'pants' || 'shorts' || 'skirt' => 'bottom',
      'onepiece' || 'costume' => 'one_piece',
      'outerwear' => 'outerwear',
      'underwear' => 'underwear',
      'bra' => 'bra',
      'panties' => 'panties',
      'socks' => 'legwear',
      'shoes' => 'footwear',
      // Accessories are stackable. Similar items still replace one another.
      'accessory' => 'accessory_${_clothingSlug(english)}',
      _ => '${scope}_garment',
    };

const _garmentScopes = <String>[
  'top',
  'pants',
  'shorts',
  'skirt',
  'onepiece',
  'outerwear',
  'costume',
  'underwear',
  'bra',
  'panties',
  'socks',
  'shoes',
  'accessory',
];

const _materials = <(String, String)>[
  ('棉質', 'cotton'),
  ('亞麻', 'linen'),
  ('羊毛', 'wool'),
  ('針織', 'knit'),
  ('羅紋針織', 'ribbed knit'),
  ('喀什米爾', 'cashmere'),
  ('丹寧', 'denim'),
  ('皮革', 'leather'),
  ('麂皮', 'suede'),
  ('絲質', 'silk'),
  ('緞面', 'satin'),
  ('雪紡', 'chiffon'),
  ('歐根紗', 'organza'),
  ('薄紗', 'tulle'),
  ('蕾絲', 'lace'),
  ('鉤針編織', 'crochet'),
  ('網眼布', 'mesh'),
  ('透視布料', 'sheer fabric'),
  ('天鵝絨', 'velvet'),
  ('燈芯絨', 'corduroy'),
  ('乳膠', 'latex'),
];

const _details = <(String, String)>[
  ('荷葉邊', 'ruffles'),
  ('褶邊', 'frills'),
  ('百褶', 'pleats'),
  ('抽褶', 'gathered fabric'),
  ('蝴蝶結', 'bow'),
  ('緞帶', 'ribbon'),
  ('蕾絲飾邊', 'lace trim'),
  ('毛皮飾邊', 'fur trim'),
  ('羽毛飾邊', 'feather trim'),
  ('刺繡', 'embroidery'),
  ('花卉刺繡', 'floral embroidery'),
  ('珠飾', 'beading'),
  ('亮片', 'sequins'),
  ('水鑽', 'rhinestones'),
  ('珍珠', 'pearls'),
  ('鈕扣', 'buttons'),
  ('拉鍊', 'zipper'),
  ('扣環', 'buckles'),
  ('腰帶', 'belt'),
  ('鏈條', 'chains'),
  ('綁帶', 'straps'),
  ('鏤空', 'cutout'),
  ('側邊鏤空', 'side cutout'),
  ('腰部鏤空', 'waist cutout'),
  ('背部鏤空', 'back cutout'),
  ('開衩', 'slit'),
  ('側開衩', 'side slit'),
  ('前開衩', 'front slit'),
  ('高開衩', 'high slit'),
  ('繫帶', 'lace-up'),
  ('馬甲繫帶', 'corset lacing'),
  ('多層次', 'layered'),
  ('垂墜', 'draped'),
  ('抓皺', 'ruched'),
  ('滾邊', 'piping'),
];

const _patterns = <(String, String)>[
  ('純色', 'solid color'),
  ('雙色', 'two-tone'),
  ('漸層', 'gradient'),
  ('撞色拼接', 'color block'),
  ('條紋', 'striped'),
  ('直條紋', 'vertical stripes'),
  ('橫條紋', 'horizontal stripes'),
  ('格紋', 'plaid'),
  ('蘇格蘭格紋', 'tartan'),
  ('棋盤格', 'checkered'),
  ('圓點', 'polka dot'),
  ('花卉印花', 'floral print'),
  ('玫瑰印花', 'rose print'),
  ('櫻花印花', 'cherry blossom print'),
  ('葉片圖案', 'leaf pattern'),
  ('幾何圖案', 'geometric pattern'),
  ('菱格紋', 'diamond pattern'),
  ('豹紋', 'leopard print'),
  ('斑馬紋', 'zebra print'),
  ('迷彩', 'camouflage'),
  ('星星圖案', 'star pattern'),
  ('愛心圖案', 'heart pattern'),
  ('角色印花', 'character print'),
  ('圖像印花', 'graphic print'),
];

const _officialClothingDimensionEnglish = <String>{
  'denim',
  'leather',
  'latex',
  'lace',
  'ruffles',
  'frills',
  'pleats',
  'bow',
  'ribbon',
  'lace trim',
  'fur trim',
  'buttons',
  'belt',
  'chains',
  'straps',
  'side slit',
  'front slit',
  'high slit',
  'off-shoulder',
  'one-shoulder',
  'halter neck',
  'sleeveless',
  'long sleeves',
  'puffy sleeves',
  'bell sleeves',
  'strapless',
  'backless',
  'high-waisted',
  'low-waisted',
  'high-cut',
  'side-tie',
  'cropped',
  'mini',
  'above knee',
  'knee length',
  'midi',
  'maxi',
  'floor length',
  'two-tone',
  'gradient',
  'striped',
  'vertical stripes',
  'horizontal stripes',
  'plaid',
  'tartan',
  'checkered',
  'polka dot',
  'floral print',
  'rose print',
  'cherry blossom print',
  'leopard print',
  'zebra print',
  'camouflage',
};

String _clothingDimensionSupport(String dimension, String english) =>
    _officialClothingDimensionEnglish.contains(english.toLowerCase())
        ? 'official'
        : 'description';

List<(String, String)> _compatibleValues(
  List<(String, String)> source,
  Set<String> allowed,
) =>
    source.where((value) => allowed.contains(value.$2)).toList();

const _materialsByScope = <String, Set<String>>{
  'top': {
    'cotton',
    'linen',
    'wool',
    'knit',
    'ribbed knit',
    'cashmere',
    'denim',
    'leather',
    'silk',
    'satin',
    'chiffon',
    'lace',
    'crochet',
    'mesh',
    'sheer fabric',
    'velvet',
    'latex'
  },
  'pants': {'cotton', 'linen', 'wool', 'denim', 'leather', 'corduroy', 'latex'},
  'shorts': {
    'cotton',
    'linen',
    'denim',
    'leather',
    'corduroy',
    'mesh',
    'latex'
  },
  'skirt': {
    'cotton',
    'linen',
    'wool',
    'denim',
    'leather',
    'silk',
    'satin',
    'chiffon',
    'organza',
    'tulle',
    'lace',
    'velvet',
    'latex'
  },
  'onepiece': {
    'cotton',
    'linen',
    'wool',
    'knit',
    'cashmere',
    'denim',
    'leather',
    'silk',
    'satin',
    'chiffon',
    'organza',
    'tulle',
    'lace',
    'crochet',
    'mesh',
    'sheer fabric',
    'velvet',
    'latex'
  },
  'outerwear': {
    'cotton',
    'wool',
    'knit',
    'cashmere',
    'denim',
    'leather',
    'suede',
    'velvet',
    'corduroy',
    'latex'
  },
  'costume': {
    'cotton',
    'linen',
    'wool',
    'denim',
    'leather',
    'silk',
    'satin',
    'chiffon',
    'organza',
    'tulle',
    'lace',
    'mesh',
    'velvet',
    'latex'
  },
  'underwear': {
    'cotton',
    'silk',
    'satin',
    'chiffon',
    'lace',
    'mesh',
    'sheer fabric'
  },
  'bra': {'cotton', 'silk', 'satin', 'lace', 'mesh', 'sheer fabric', 'latex'},
  'panties': {
    'cotton',
    'silk',
    'satin',
    'lace',
    'mesh',
    'sheer fabric',
    'latex'
  },
  'socks': {'cotton', 'wool', 'knit', 'lace', 'mesh'},
  'shoes': {'denim', 'leather', 'suede', 'mesh', 'latex'},
  'accessory': {
    'cotton',
    'wool',
    'knit',
    'denim',
    'leather',
    'suede',
    'silk',
    'satin',
    'lace',
    'velvet',
    'latex'
  },
};

const _detailsByScope = <String, Set<String>>{
  'top': {
    'ruffles',
    'frills',
    'pleats',
    'gathered fabric',
    'bow',
    'ribbon',
    'lace trim',
    'fur trim',
    'feather trim',
    'embroidery',
    'floral embroidery',
    'beading',
    'sequins',
    'rhinestones',
    'pearls',
    'buttons',
    'zipper',
    'buckles',
    'belt',
    'chains',
    'straps',
    'cutout',
    'side cutout',
    'waist cutout',
    'back cutout',
    'lace-up',
    'corset lacing',
    'layered',
    'draped',
    'ruched',
    'piping'
  },
  'pants': {
    'pleats',
    'bow',
    'ribbon',
    'embroidery',
    'buttons',
    'zipper',
    'buckles',
    'belt',
    'chains',
    'straps',
    'side cutout',
    'lace-up',
    'piping'
  },
  'shorts': {
    'ruffles',
    'frills',
    'pleats',
    'bow',
    'ribbon',
    'lace trim',
    'embroidery',
    'buttons',
    'zipper',
    'buckles',
    'belt',
    'straps',
    'side cutout',
    'lace-up',
    'piping'
  },
  'skirt': {
    'ruffles',
    'frills',
    'pleats',
    'gathered fabric',
    'bow',
    'ribbon',
    'lace trim',
    'fur trim',
    'feather trim',
    'embroidery',
    'floral embroidery',
    'beading',
    'sequins',
    'rhinestones',
    'pearls',
    'buttons',
    'zipper',
    'buckles',
    'belt',
    'chains',
    'straps',
    'cutout',
    'side cutout',
    'waist cutout',
    'slit',
    'side slit',
    'front slit',
    'high slit',
    'lace-up',
    'layered',
    'draped',
    'ruched',
    'piping'
  },
  'onepiece': {
    'ruffles',
    'frills',
    'pleats',
    'gathered fabric',
    'bow',
    'ribbon',
    'lace trim',
    'fur trim',
    'feather trim',
    'embroidery',
    'floral embroidery',
    'beading',
    'sequins',
    'rhinestones',
    'pearls',
    'buttons',
    'zipper',
    'buckles',
    'belt',
    'chains',
    'straps',
    'cutout',
    'side cutout',
    'waist cutout',
    'back cutout',
    'slit',
    'side slit',
    'front slit',
    'high slit',
    'lace-up',
    'corset lacing',
    'layered',
    'draped',
    'ruched',
    'piping'
  },
  'outerwear': {
    'ruffles',
    'frills',
    'bow',
    'ribbon',
    'lace trim',
    'fur trim',
    'feather trim',
    'embroidery',
    'beading',
    'sequins',
    'buttons',
    'zipper',
    'buckles',
    'belt',
    'chains',
    'straps',
    'lace-up',
    'piping'
  },
  'costume': {
    'ruffles',
    'frills',
    'pleats',
    'bow',
    'ribbon',
    'lace trim',
    'fur trim',
    'embroidery',
    'floral embroidery',
    'beading',
    'sequins',
    'pearls',
    'buttons',
    'zipper',
    'buckles',
    'belt',
    'chains',
    'straps',
    'cutout',
    'side cutout',
    'waist cutout',
    'back cutout',
    'slit',
    'side slit',
    'front slit',
    'high slit',
    'lace-up',
    'layered',
    'piping'
  },
  'underwear': {
    'ruffles',
    'frills',
    'bow',
    'ribbon',
    'lace trim',
    'embroidery',
    'pearls',
    'straps',
    'cutout',
    'lace-up'
  },
  'bra': {
    'ruffles',
    'frills',
    'bow',
    'ribbon',
    'lace trim',
    'embroidery',
    'pearls',
    'straps',
    'cutout',
    'lace-up'
  },
  'panties': {
    'ruffles',
    'frills',
    'bow',
    'ribbon',
    'lace trim',
    'embroidery',
    'pearls',
    'straps',
    'cutout',
    'side cutout',
    'lace-up'
  },
  'socks': {
    'ruffles',
    'frills',
    'bow',
    'ribbon',
    'lace trim',
    'embroidery',
    'straps',
    'lace-up'
  },
  'shoes': {
    'ruffles',
    'frills',
    'bow',
    'ribbon',
    'lace trim',
    'fur trim',
    'embroidery',
    'beading',
    'sequins',
    'rhinestones',
    'pearls',
    'buttons',
    'zipper',
    'buckles',
    'chains',
    'straps',
    'cutout',
    'lace-up',
    'piping'
  },
  'accessory': {
    'ruffles',
    'frills',
    'bow',
    'ribbon',
    'lace trim',
    'fur trim',
    'feather trim',
    'embroidery',
    'beading',
    'sequins',
    'rhinestones',
    'pearls',
    'buttons',
    'zipper',
    'buckles',
    'chains',
    'straps',
    'lace-up',
    'piping'
  },
};

const _patternScopes = <String>{
  'top',
  'pants',
  'shorts',
  'skirt',
  'onepiece',
  'outerwear',
  'costume',
  'underwear',
  'bra',
  'panties',
  'socks',
  'shoes',
  'accessory'
};

/// Clothing data follows a composable taxonomy. Garment nouns stay separate
/// from cut, fit, length, material, detail, pattern, color, and overall style.
final List<CatalogTagData> clothingTaxonomyTags = <CatalogTagData>[
  ..._garments('上衣', 'top', const [
    ('T恤', 't-shirt'),
    ('襯衫', 'shirt'),
    ('正裝襯衫', 'dress shirt'),
    ('鈕扣襯衫', 'button-up shirt'),
    ('牛津襯衫', 'Oxford shirt'),
    ('女式襯衫', 'blouse'),
    ('翻領女式襯衫', 'collared blouse'),
    ('背心', 'tank top'),
    ('細肩帶上衣', 'camisole'),
    ('短版上衣', 'crop top'),
    ('平口上衣', 'tube top'),
    ('繞頸上衣', 'halter top'),
    ('針織上衣', 'knit top'),
    ('毛衣', 'sweater'),
    ('開襟衫', 'cardigan'),
    ('連帽上衣', 'hoodie'),
    ('運動衫', 'sweatshirt'),
    ('馬甲上衣', 'corset top'),
    ('西裝背心', 'suit vest'),
    ('籃球球衣', 'basketball jersey'),
  ]),
  ..._garments('褲子', 'pants', const [
    ('直筒褲', 'straight-leg pants'),
    ('窄管褲', 'narrow-leg pants'),
    ('緊身褲', 'skinny pants'),
    ('寬褲', 'wide-leg pants'),
    ('喇叭褲', 'flared pants'),
    ('錐形褲', 'tapered pants'),
    ('九分褲', 'cropped pants'),
    ('牛仔褲', 'jeans'),
    ('西裝褲', 'dress pants'),
    ('工裝褲', 'cargo pants'),
    ('慢跑褲', 'joggers'),
    ('運動長褲', 'sweatpants'),
    ('內搭褲', 'leggings'),
    ('皮褲', 'leather pants'),
  ]),
  ..._garments('短褲', 'shorts', const [
    ('短褲', 'shorts'),
    ('熱褲', 'hot pants'),
    ('高腰短褲', 'high-waisted shorts'),
    ('丹寧短褲', 'denim shorts'),
    ('百慕達短褲', 'Bermuda shorts'),
    ('運動短褲', 'sports shorts'),
    ('自行車短褲', 'bike shorts'),
    ('工裝短褲', 'cargo shorts'),
    ('燈籠短褲', 'bloomers'),
  ]),
  ..._garments('裙子', 'skirt', const [
    ('A字裙', 'a-line skirt'),
    ('鉛筆裙', 'pencil skirt'),
    ('百褶裙', 'pleated skirt'),
    ('圓裙', 'circle skirt'),
    ('傘裙', 'flared skirt'),
    ('包裙', 'wrap skirt'),
    ('分層裙', 'tiered skirt'),
    ('魚尾裙', 'mermaid skirt'),
    ('芭蕾舞裙', 'tutu'),
    ('牛仔裙', 'denim skirt'),
    ('運動裙', 'sports skirt'),
  ]),
  ..._garments('服裝', 'onepiece', const [
    ('洋裝', 'dress'),
    ('晚禮服', 'evening gown'),
    ('雞尾酒洋裝', 'cocktail dress'),
    ('背心裙', 'sundress'),
    ('襯衫裙', 'shirt dress'),
    ('針織洋裝', 'knit dress'),
    ('包裹式洋裝', 'wrap dress'),
    ('吊帶洋裝', 'slip dress'),
    ('舞會禮服', 'ball gown'),
    ('連身褲', 'jumpsuit'),
    ('連身短褲', 'romper'),
  ]),
  ..._garments('外套', 'outerwear', const [
    ('西裝外套', 'blazer'),
    ('夾克', 'jacket'),
    ('牛仔外套', 'denim jacket'),
    ('皮夾克', 'leather jacket'),
    ('飛行夾克', 'bomber jacket'),
    ('運動外套', 'track jacket'),
    ('風衣', 'trench coat'),
    ('大衣', 'coat'),
    ('斗篷', 'cape'),
    ('披肩', 'shawl'),
    ('雨衣', 'raincoat'),
    ('實驗袍', 'lab coat'),
  ]),
  ..._garments('特殊服裝', 'costume', const [
    ('女僕', 'maid'),
    ('護士服', 'nurse uniform'),
    ('警察制服', 'police uniform'),
    ('軍服', 'military uniform'),
    ('啦啦隊服', 'cheerleading uniform'),
    ('和服', 'kimono'),
    ('浴衣', 'yukata'),
    ('巫女', 'miko'),
    ('武術服', 'martial arts uniform'),
    ('體操服', 'gymnastics leotard'),
    ('泳裝', 'swimsuit'),
    ('婚紗', 'wedding dress'),
  ]),
  ..._garments(
      '特殊服裝',
      'costume',
      const [
        ('正式西裝外套套裝', 'formal blazer outfit'),
        ('水手風套裝', 'sailor-style outfit'),
        ('運動制服', 'sports uniform'),
        ('弓道服', 'kyudo uniform'),
        ('忍者套裝', 'ninja outfit'),
        ('黑魔導女孩服裝', 'Dark Magician Girl outfit'),
      ],
      support: 'description'),
  ..._garments(
      '內衣',
      'underwear',
      const [
        ('女性內衣', 'lingerie'),
        ('娃娃裝內衣', 'babydoll'),
        ('連身絲襪', 'bodystocking'),
        ('馬甲內衣', 'bustier'),
        ('細肩帶內衣', 'camisole'),
        ('襯裙式內衣', 'chemise'),
        ('束腰', 'corset'),
        ('睡裙', 'nightgown'),
        ('連身式情趣內衣', 'teddy'),
      ],
      adult: true),
  ..._garments(
      '胸罩',
      'bra',
      const [
        ('胸罩', 'bra'),
        ('運動胸罩', 'sports bra'),
        ('無肩帶胸罩', 'strapless bra'),
        ('無罩杯胸罩', 'cupless bra'),
        ('蕾絲胸罩', 'lace bra'),
      ],
      adult: true),
  ..._garments(
      '內褲',
      'panties',
      const [
        ('內褲', 'panties'),
        ('平口女內褲', 'boyshort panties'),
        ('丁字褲', 'thong'),
        ('細帶丁字褲', 'g-string'),
        ('珍珠丁字褲', 'pearl thong'),
        ('開襠內褲', 'crotchless panties'),
      ],
      adult: true),
  ..._garments('襪子', 'socks', const [
    ('短襪', 'socks'),
    ('及膝襪', 'kneehighs'),
    ('過膝襪', 'over-kneehighs'),
    ('大腿襪', 'thighhighs'),
    ('高衩大腿襪', 'hiphighs'),
    ('連褲襪', 'pantyhose'),
    ('內搭褲', 'leggings'),
    ('網襪', 'fishnets'),
    ('分趾襪', 'tabi'),
  ]),
  ..._garments('配件', 'accessory', const [
    ('帽子', 'hat'),
    ('貝雷帽', 'beret'),
    ('棒球帽', 'baseball cap'),
    ('鴨舌帽', 'cap'),
    ('毛帽', 'beanie'),
    ('漁夫帽', 'bucket hat'),
    ('牛仔帽', 'cowboy hat'),
    ('費多拉帽', 'fedora'),
    ('遮陽帽', 'sun hat'),
    ('草帽', 'straw hat'),
    ('巫師帽', 'witch hat'),
    ('高頂禮帽', 'top hat'),
    ('水手帽', 'sailor hat'),
    ('軍帽', 'military hat'),
    ('頭盔', 'helmet'),
    ('鐘形帽', 'cloche hat'),
    ('三角帽', 'tricorne'),
    ('帽兜', 'hood'),
    ('王冠', 'crown'),
    ('頭飾', 'headdress'),
    ('花環', 'head wreath'),
    ('光環', 'halo'),
    ('髮帶', 'headband'),
    ('蝴蝶結髮飾', 'hair bow'),
    ('大蝴蝶結髮飾', 'large hair bow'),
    ('髮夾', 'hairclip'),
    ('髮飾', 'hair ornament'),
    ('髮帶蝴蝶結', 'hair ribbon'),
    ('髮花', 'hair flower'),
    ('髮圈', 'hair scrunchie'),
    ('髮珠', 'hair beads'),
    ('髮環', 'hair rings'),
    ('髮簪', 'hair stick'),
    ('蝴蝶結髮帶', 'bow hairband'),
    ('皇冠', 'tiara'),
    ('頭紗', 'veil'),
    ('眼鏡', 'glasses'),
    ('太陽眼鏡', 'sunglasses'),
    ('護目鏡', 'goggles'),
    ('滑雪護目鏡', 'ski goggles'),
    ('泳鏡', 'swim goggles'),
    ('單片眼鏡', 'monocle'),
    ('眼罩', 'eyepatch'),
    ('圓框眼鏡', 'round eyewear'),
    ('橢圓框眼鏡', 'oval eyewear'),
    ('方框眼鏡', 'square eyewear'),
    ('貓眼眼鏡', 'cat-eye eyewear'),
    ('心形眼鏡', 'heart-shaped eyewear'),
    ('星形眼鏡', 'star-shaped eyewear'),
    ('半框眼鏡', 'half-rim eyewear'),
    ('無框眼鏡', 'rimless eyewear'),
    ('安全護目鏡', 'safety goggles'),
    ('口罩', 'surgical mask'),
    ('耳環', 'earrings'),
    ('耳骨夾', 'ear cuffs'),
    ('頸圈', 'choker'),
    ('項鍊', 'necklace'),
    ('領帶', 'necktie'),
    ('領結', 'neck ribbon'),
    ('圍巾', 'scarf'),
    ('披肩', 'shawl'),
    ('腰帶', 'belt'),
    ('手套', 'gloves'),
    ('無指手套', 'fingerless gloves'),
  ]),
  ..._garments('鞋子', 'shoes', const [
    // 基本／休閒鞋型
    ('鞋子', 'shoes'),
    ('運動鞋', 'sneakers'),
    ('帆布鞋', 'canvas shoes'),
    ('懶人鞋', 'slip-on shoes'),
    ('平底鞋', 'flats'),
    ('芭蕾平底鞋', 'ballet flats'),
    ('樂福鞋', 'loafers'),
    ('莫卡辛鞋', 'moccasins'),
    ('牛津鞋', 'oxfords'),
    ('德比鞋', 'derby shoes'),
    ('雕花皮鞋', 'brogues'),
    ('孟克鞋', 'monk strap shoes'),
    ('船鞋', 'boat shoes'),
    ('草編鞋', 'espadrilles'),
    ('室內校園鞋', 'uwabaki'),
    // 高跟／厚底鞋型
    ('高跟鞋', 'high heels'),
    ('淺口高跟鞋', 'pumps'),
    ('細高跟鞋', 'stiletto heels'),
    ('低跟鞋', 'kitten heels'),
    ('楔形跟鞋', 'wedge heels'),
    ('厚底鞋', 'platform shoes'),
    ('厚底高跟鞋', 'platform heels'),
    ('露跟鞋', 'slingback shoes'),
    ('魚口高跟鞋', 'peep-toe heels'),
    ('踝帶高跟鞋', 'ankle strap heels'),
    ('瑪莉珍鞋', 'mary janes'),
    // 涼鞋／拖鞋
    ('涼鞋', 'sandals'),
    ('繫帶涼鞋', 'strappy sandals'),
    ('羅馬涼鞋', 'gladiator sandals'),
    ('厚底涼鞋', 'platform sandals'),
    ('夾腳拖鞋', 'flip-flops'),
    ('一字拖鞋', 'slides'),
    ('室內拖鞋', 'house slippers'),
    ('拖鞋', 'slippers'),
    ('木底鞋', 'clogs'),
    // 靴類
    ('靴子', 'boots'),
    ('踝靴', 'ankle boots'),
    ('及膝靴', 'knee boots'),
    ('過膝靴', 'over-the-knee boots'),
    ('大腿靴', 'thigh boots'),
    ('戰鬥靴', 'combat boots'),
    ('登山靴', 'hiking boots'),
    ('牛仔靴', 'cowboy boots'),
    ('馬術靴', 'riding boots'),
    ('切爾西靴', 'Chelsea boots'),
    ('綁帶靴', 'lace-up boots'),
    ('厚底靴', 'platform boots'),
    ('雨靴', 'rain boots'),
    ('雪靴', 'snow boots'),
    ('冬季靴', 'winter boots'),
    // 運動／專用鞋
    ('跑鞋', 'running shoes'),
    ('籃球鞋', 'basketball shoes'),
    ('網球鞋', 'tennis shoes'),
    ('足球釘鞋', 'soccer cleats'),
    ('高爾夫球鞋', 'golf shoes'),
    ('保齡球鞋', 'bowling shoes'),
    ('自行車鞋', 'cycling shoes'),
    ('攀岩鞋', 'climbing shoes'),
    ('舞鞋', 'dance shoes'),
    ('芭蕾足尖鞋', 'pointe shoes'),
    ('踢踏舞鞋', 'tap shoes'),
    ('冰刀鞋', 'ice skates'),
    ('輪式溜冰鞋', 'roller skates'),
    // 日式傳統鞋型
    ('木屐', 'geta'),
    ('草履', 'zouri'),
    ('分趾靴', 'tabi boots'),
  ]),
];

final List<CatalogTagData> clothingDimensionTags = <CatalogTagData>[
  for (final scope in _garmentScopes)
    ..._dimensions(
      scope,
      'material',
      _compatibleValues(
          _materials, _materialsByScope[scope] ?? const <String>{}),
    ),
  for (final scope in _garmentScopes)
    ..._dimensions(
      scope,
      'detail',
      _compatibleValues(_details, _detailsByScope[scope] ?? const <String>{}),
    ),
  for (final scope in _garmentScopes)
    if (_patternScopes.contains(scope))
      ..._dimensions(scope, 'pattern', _patterns),
  for (final scope in const [
    'top',
    'pants',
    'shorts',
    'skirt',
    'onepiece',
    'outerwear'
  ])
    ..._dimensions(scope, 'fit', const [
      ('貼身', 'fitted'),
      ('修身剪裁', 'tailored fit'),
      ('合身', 'regular fit'),
      ('寬鬆', 'loose fit'),
      ('超寬鬆', 'oversized'),
      ('垂墜版型', 'relaxed fit'),
      ('箱型版型', 'boxy fit'),
    ]),
  ..._dimensions('top', 'cut', const [
    ('圓領', 'crew neck'),
    ('V領', 'v-neck'),
    ('高領', 'turtleneck'),
    ('立領', 'stand collar'),
    ('一字領', 'boat neck'),
    ('露肩', 'off-shoulder'),
    ('單肩', 'one-shoulder'),
    ('繞頸', 'halter neck'),
    ('無袖', 'sleeveless'),
    ('肘上袖', 'above-elbow sleeves'),
    ('長袖', 'long sleeves'),
    ('泡泡袖', 'puffy sleeves'),
    ('喇叭袖', 'bell sleeves'),
    ('削肩', 'racerback'),
  ]),
  for (final scope in const ['pants', 'shorts', 'skirt', 'onepiece'])
    ..._dimensions(scope, 'cut', const [
      ('自然腰', 'natural waist'),
      ('高腰', 'high-waisted'),
      ('低腰', 'low-waisted'),
      ('帝王腰線', 'empire waist'),
      ('低腰線', 'drop waist'),
    ]),
  ..._dimensions('onepiece', 'cut', const [
    ('無肩帶', 'strapless'),
    ('單肩', 'one-shoulder'),
    ('露肩', 'off-shoulder'),
    ('繞頸', 'halter neck'),
    ('露背', 'backless'),
    ('深V領', 'plunging neckline'),
  ]),
  ..._dimensions('bra', 'cut', const [
    ('有鋼圈', 'underwire'),
    ('無鋼圈', 'wireless'),
    ('集中托高', 'push-up'),
    ('無肩帶', 'strapless'),
    ('三角罩杯', 'triangle cups'),
    ('前扣', 'front clasp'),
  ]),
  ..._dimensions('panties', 'cut', const [
    ('高腰', 'high-waisted'),
    ('低腰', 'low-rise'),
    ('高衩', 'high-cut'),
    ('低衩', 'low-cut'),
    ('側綁帶', 'side-tie'),
    ('無痕', 'seamless'),
  ]),
  ..._dimensions('top', 'length', const [
    ('超短版', 'ultra cropped'),
    ('短版', 'cropped'),
    ('及腰', 'waist length'),
    ('及臀', 'hip length'),
    ('加長版', 'longline'),
  ]),
  ..._dimensions('pants', 'length', const [
    ('七分長', 'cropped length'),
    ('九分長', 'ankle length'),
    ('全長', 'full length'),
  ]),
  ..._dimensions('shorts', 'length', const [
    ('極短', 'micro length'),
    ('大腿上段長度', 'upper-thigh length'),
    ('百慕達長度', 'Bermuda length'),
  ]),
  for (final scope in const ['skirt', 'onepiece'])
    ..._dimensions(scope, 'length', const [
      ('極短', 'micro'),
      ('迷你', 'mini'),
      ('膝上', 'above knee'),
      ('及膝', 'knee length'),
      ('中長', 'midi'),
      ('小腿長', 'calf length'),
      ('腳踝長', 'ankle length'),
      ('長裙', 'maxi'),
      ('拖地長度', 'floor length'),
    ]),
  ..._dimensions('outerwear', 'length', const [
    ('短版', 'cropped'),
    ('及臀', 'hip length'),
    ('及膝', 'knee length'),
    ('長版', 'long'),
  ]),
  // Legwear height is a garment type (kneehighs, thighhighs, etc.), not a
  // generic sock plus a free-form length modifier.
];

final List<CatalogTagData> clothingOverallTags = <CatalogTagData>[
  ..._overall('outfit_main_style', '服裝・主要風格', const [
    ('休閒', 'casual'),
    ('女性化', 'feminine'),
    ('俏麗', 'charming'),
    ('優雅', 'elegant'),
    ('性感', 'sexy'),
    ('學院', 'preppy'),
    ('街頭', 'streetwear'),
    ('運動', 'sportswear'),
    ('哥德', 'goth fashion'),
    ('龐克', 'punk'),
    ('復古', 'vintage'),
    ('極簡', 'minimalist'),
    ('波希米亞', 'bohemian'),
    ('奇幻', 'fantasy'),
    ('未來感', 'futuristic'),
  ]),
  ..._overall('outfit_sub_style', '服裝・子風格', const [
    ('輕鬆休閒', 'relaxed casual style'),
    ('正式休閒', 'smart casual style'),
    ('浪漫女性化', 'romantic feminine style'),
    ('甜美女性化', 'sweet feminine style'),
    ('經典優雅', 'classic elegant style'),
    ('華麗性感', 'glamorous sexy style'),
    ('都市街頭', 'urban streetwear style'),
    ('機能服飾', 'techwear style'),
    ('運動休閒', 'athleisure style'),
    ('浪漫哥德', 'romantic gothic style'),
    ('維多利亞哥德', 'Victorian gothic style'),
    ('黑暗哥德', 'dark gothic style'),
    ('蒸汽龐克', 'steampunk style'),
    ('Y2K復古', 'Y2K fashion'),
    ('現代極簡', 'modern minimal style'),
    ('中世紀奇幻', 'medieval fantasy style'),
    ('公主奇幻', 'princess fantasy style'),
    ('女巫奇幻', 'witch fantasy style'),
    ('賽博龐克', 'cyberpunk style'),
  ]),
  ..._overall('outfit_mood', '服裝・氣質', const [
    ('明快氣質', 'cheerful mood'),
    ('甜美氣質', 'sweet mood'),
    ('清純氣質', 'innocent mood'),
    ('優雅氣質', 'elegant mood'),
    ('成熟氣質', 'mature mood'),
    ('性感氣質', 'sexy mood'),
    ('冷酷氣質', 'cool mood'),
    ('強悍氣質', 'tough mood'),
    ('運動氣質', 'sporty mood'),
    ('正式氣質', 'formal mood'),
    ('奢華氣質', 'luxurious mood'),
    ('浪漫氣質', 'romantic mood'),
    ('神祕氣質', 'mysterious mood'),
    ('黑暗氣質', 'dark mood'),
    ('活潑氣質', 'playful mood'),
  ]),
  ..._overall('outfit_occasion', '服裝・場合', const [
    ('日常穿搭', 'daily outfit'),
    ('休閒外出', 'casual outing outfit'),
    ('約會穿搭', 'date outfit'),
    ('咖啡廳穿搭', 'cafe outfit'),
    ('旅行穿搭', 'travel outfit'),
    ('工作穿搭', 'work outfit'),
    ('辦公室穿搭', 'office outfit'),
    ('商務休閒', 'business casual outfit'),
    ('日間正式穿搭', 'daytime formal outfit'),
    ('運動穿搭', 'sports outfit'),
    ('健身房穿搭', 'gym outfit'),
    ('戶外穿搭', 'outdoor outfit'),
    ('派對穿搭', 'party outfit'),
    ('正式活動', 'formal event outfit'),
    ('婚禮賓客', 'wedding guest outfit'),
    ('海灘穿搭', 'beach outfit'),
    ('居家服', 'homewear outfit'),
    ('睡衣穿搭', 'sleepwear outfit'),
  ]),
];
