import 'catalog_data.dart';

/// Additional everyday visual props. They retain the base 物件 group so
/// existing saved selections and object-interaction actions remain compatible;
/// the UI classifies them through their stable ID prefixes.
const objectCatalogTags = <CatalogTagData>[
  // 家具／室內（14）
  CatalogTagData(id: 'obj_furniture_armchair', group: '物件', zh: '扶手椅', en: 'armchair', order: 4),
  CatalogTagData(id: 'obj_furniture_stool', group: '物件', zh: '凳子', en: 'stool', order: 4),
  CatalogTagData(id: 'obj_furniture_bench', group: '物件', zh: '長椅', en: 'bench', order: 4),
  CatalogTagData(id: 'obj_furniture_desk', group: '物件', zh: '書桌', en: 'desk', order: 4),
  CatalogTagData(id: 'obj_furniture_dining_table', group: '物件', zh: '餐桌', en: 'dining table', order: 4),
  CatalogTagData(id: 'obj_furniture_coffee_table', group: '物件', zh: '茶几', en: 'coffee table', order: 4),
  CatalogTagData(id: 'obj_furniture_nightstand', group: '物件', zh: '床頭櫃', en: 'nightstand', order: 4),
  CatalogTagData(id: 'obj_furniture_bookshelf', group: '物件', zh: '書架', en: 'bookshelf', order: 4),
  CatalogTagData(id: 'obj_furniture_wardrobe', group: '物件', zh: '衣櫃', en: 'wardrobe', order: 4),
  CatalogTagData(id: 'obj_furniture_dresser', group: '物件', zh: '抽屜櫃', en: 'dresser', order: 4),
  CatalogTagData(id: 'obj_furniture_floor_mirror', group: '物件', zh: '全身鏡', en: 'floor mirror', order: 4),
  CatalogTagData(id: 'obj_furniture_floor_lamp', group: '物件', zh: '立燈', en: 'floor lamp', order: 4),
  CatalogTagData(id: 'obj_furniture_chandelier', group: '物件', zh: '吊燈', en: 'chandelier', order: 4),
  CatalogTagData(id: 'obj_furniture_rug', group: '物件', zh: '地毯', en: 'rug', order: 4),

  // 飲食／餐具（12）
  CatalogTagData(id: 'obj_food_bento', group: '物件', zh: '便當盒', en: 'bento', order: 4),
  CatalogTagData(id: 'obj_food_lunchbox', group: '物件', zh: '午餐盒', en: 'lunchbox', order: 4),
  CatalogTagData(id: 'obj_food_tray', group: '物件', zh: '托盤', en: 'tray', order: 4),
  CatalogTagData(id: 'obj_food_teapot', group: '物件', zh: '茶壺', en: 'teapot', order: 4),
  CatalogTagData(id: 'obj_food_kettle', group: '物件', zh: '水壺', en: 'kettle', order: 4),
  CatalogTagData(id: 'obj_food_wine_glass', group: '物件', zh: '紅酒杯', en: 'wine glass', order: 4),
  CatalogTagData(id: 'obj_food_cocktail_glass', group: '物件', zh: '雞尾酒杯', en: 'cocktail glass', order: 4),
  CatalogTagData(id: 'obj_food_frying_pan', group: '物件', zh: '平底鍋', en: 'frying pan', order: 4),
  CatalogTagData(id: 'obj_food_cutting_board', group: '物件', zh: '砧板', en: 'cutting board', order: 4),
  CatalogTagData(id: 'obj_food_rice_ball', group: '物件', zh: '飯糰', en: 'rice ball', order: 4),
  CatalogTagData(id: 'obj_food_sandwich', group: '物件', zh: '三明治', en: 'sandwich', order: 4),
  CatalogTagData(id: 'obj_food_pizza', group: '物件', zh: '披薩', en: 'pizza', order: 4),

  // 學習／藝術／音樂（14）
  CatalogTagData(id: 'obj_study_fountain_pen', group: '物件', zh: '鋼筆', en: 'fountain pen', order: 4),
  CatalogTagData(id: 'obj_study_marker', group: '物件', zh: '麥克筆', en: 'marker', order: 4),
  CatalogTagData(id: 'obj_study_ruler', group: '物件', zh: '尺', en: 'ruler', order: 4),
  CatalogTagData(id: 'obj_study_scissors', group: '物件', zh: '剪刀', en: 'scissors', order: 4),
  CatalogTagData(id: 'obj_study_clipboard', group: '物件', zh: '寫字板', en: 'clipboard', order: 4),
  CatalogTagData(id: 'obj_study_chalk', group: '物件', zh: '粉筆', en: 'chalk', order: 4),
  CatalogTagData(id: 'obj_study_blackboard', group: '物件', zh: '黑板', en: 'blackboard', order: 4),
  CatalogTagData(id: 'obj_study_paper', group: '物件', zh: '紙張', en: 'paper', order: 4),
  CatalogTagData(id: 'obj_study_letter', group: '物件', zh: '信件', en: 'letter', order: 4),
  CatalogTagData(id: 'obj_study_newspaper', group: '物件', zh: '報紙', en: 'newspaper', order: 4),
  CatalogTagData(id: 'obj_study_map', group: '物件', zh: '地圖', en: 'map', order: 4),
  CatalogTagData(id: 'obj_study_globe', group: '物件', zh: '地球儀', en: 'globe', order: 4),
  CatalogTagData(id: 'obj_study_sketchbook', group: '物件', zh: '素描本', en: 'sketchbook', order: 4),
  CatalogTagData(id: 'obj_study_paint_tube', group: '物件', zh: '顏料管', en: 'paint tube', order: 4),

  // 科技／媒體（10）
  CatalogTagData(id: 'obj_tech_desktop_computer', group: '物件', zh: '桌上型電腦', en: 'desktop computer', order: 4),
  CatalogTagData(id: 'obj_tech_monitor', group: '物件', zh: '螢幕', en: 'monitor', order: 4),
  CatalogTagData(id: 'obj_tech_keyboard', group: '物件', zh: '鍵盤', en: 'keyboard', order: 4),
  CatalogTagData(id: 'obj_tech_mouse', group: '物件', zh: '滑鼠', en: 'mouse', order: 4),
  CatalogTagData(id: 'obj_tech_game_controller', group: '物件', zh: '遊戲手把', en: 'game controller', order: 4),
  CatalogTagData(id: 'obj_tech_handheld_console', group: '物件', zh: '掌上遊戲機', en: 'handheld game console', order: 4),
  CatalogTagData(id: 'obj_tech_television', group: '物件', zh: '電視', en: 'television', order: 4),
  CatalogTagData(id: 'obj_tech_projector', group: '物件', zh: '投影機', en: 'projector', order: 4),
  CatalogTagData(id: 'obj_tech_speaker', group: '物件', zh: '喇叭', en: 'speaker', order: 4),
  CatalogTagData(id: 'obj_tech_drone', group: '物件', zh: '無人機', en: 'drone', order: 4),

  // 運動／戶外（12）
  CatalogTagData(id: 'obj_sport_tennis_ball', group: '物件', zh: '網球', en: 'tennis ball', order: 4),
  CatalogTagData(id: 'obj_sport_golf_club', group: '物件', zh: '高爾夫球桿', en: 'golf club', order: 4),
  CatalogTagData(id: 'obj_sport_golf_ball', group: '物件', zh: '高爾夫球', en: 'golf ball', order: 4),
  CatalogTagData(id: 'obj_sport_bowling_ball', group: '物件', zh: '保齡球', en: 'bowling ball', order: 4),
  CatalogTagData(id: 'obj_sport_dumbbell', group: '物件', zh: '啞鈴', en: 'dumbbell', order: 4),
  CatalogTagData(id: 'obj_sport_barbell', group: '物件', zh: '槓鈴', en: 'barbell', order: 4),
  CatalogTagData(id: 'obj_sport_jump_rope', group: '物件', zh: '跳繩', en: 'jump rope', order: 4),
  CatalogTagData(id: 'obj_sport_boxing_gloves', group: '物件', zh: '拳擊手套', en: 'boxing gloves', order: 4),
  CatalogTagData(id: 'obj_sport_punching_bag', group: '物件', zh: '沙包', en: 'punching bag', order: 4),
  CatalogTagData(id: 'obj_sport_yoga_mat', group: '物件', zh: '瑜伽墊', en: 'yoga mat', order: 4),
  CatalogTagData(id: 'obj_sport_surfboard', group: '物件', zh: '衝浪板', en: 'surfboard', order: 4),
  CatalogTagData(id: 'obj_sport_fishing_rod', group: '物件', zh: '釣竿', en: 'fishing rod', order: 4),

  // 工具／科學／遊戲（12）
  CatalogTagData(id: 'obj_tool_hammer', group: '物件', zh: '鐵鎚', en: 'hammer', order: 4),
  CatalogTagData(id: 'obj_tool_wrench', group: '物件', zh: '扳手', en: 'wrench', order: 4),
  CatalogTagData(id: 'obj_tool_screwdriver', group: '物件', zh: '螺絲起子', en: 'screwdriver', order: 4),
  CatalogTagData(id: 'obj_tool_pliers', group: '物件', zh: '鉗子', en: 'pliers', order: 4),
  CatalogTagData(id: 'obj_tool_measuring_tape', group: '物件', zh: '捲尺', en: 'measuring tape', order: 4),
  CatalogTagData(id: 'obj_tool_sewing_machine', group: '物件', zh: '縫紉機', en: 'sewing machine', order: 4),
  CatalogTagData(id: 'obj_tool_watering_can', group: '物件', zh: '澆水壺', en: 'watering can', order: 4),
  CatalogTagData(id: 'obj_tool_toolbox', group: '物件', zh: '工具箱', en: 'toolbox', order: 4),
  CatalogTagData(id: 'obj_tool_microscope', group: '物件', zh: '顯微鏡', en: 'microscope', order: 4),
  CatalogTagData(id: 'obj_tool_telescope', group: '物件', zh: '望遠鏡', en: 'telescope', order: 4),
  CatalogTagData(id: 'obj_tool_test_tube', group: '物件', zh: '試管', en: 'test tube', order: 4),
  CatalogTagData(id: 'obj_tool_chessboard', group: '物件', zh: '西洋棋盤', en: 'chessboard', order: 4),

  // 武器／奇幻（12）
  CatalogTagData(id: 'obj_fantasy_dagger', group: '物件', zh: '匕首', en: 'dagger', order: 4),
  CatalogTagData(id: 'obj_fantasy_axe', group: '物件', zh: '斧頭', en: 'axe', order: 4),
  CatalogTagData(id: 'obj_fantasy_spear', group: '物件', zh: '長矛', en: 'spear', order: 4),
  CatalogTagData(id: 'obj_fantasy_lance', group: '物件', zh: '騎槍', en: 'lance', order: 4),
  CatalogTagData(id: 'obj_fantasy_scythe', group: '物件', zh: '鐮刀', en: 'scythe', order: 4),
  CatalogTagData(id: 'obj_fantasy_crossbow', group: '物件', zh: '十字弓', en: 'crossbow', order: 4),
  CatalogTagData(id: 'obj_fantasy_pistol', group: '物件', zh: '手槍', en: 'pistol', order: 4),
  CatalogTagData(id: 'obj_fantasy_magic_book', group: '物件', zh: '魔法書', en: 'magic book', order: 4),
  CatalogTagData(id: 'obj_fantasy_crystal_ball', group: '物件', zh: '水晶球', en: 'crystal ball', order: 4),
  CatalogTagData(id: 'obj_fantasy_potion_bottle', group: '物件', zh: '藥水瓶', en: 'potion bottle', order: 4),
  CatalogTagData(id: 'obj_fantasy_treasure_chest', group: '物件', zh: '寶箱', en: 'treasure chest', order: 4),
  CatalogTagData(id: 'obj_fantasy_crown', group: '物件', zh: '王冠', en: 'crown', order: 4),

  // 交通／旅行（11）
  CatalogTagData(id: 'obj_travel_suitcase', group: '物件', zh: '行李箱', en: 'suitcase', order: 4),
  CatalogTagData(id: 'obj_travel_rolling_suitcase', group: '物件', zh: '拉桿行李箱', en: 'rolling suitcase', order: 4),
  CatalogTagData(id: 'obj_travel_shopping_bag', group: '物件', zh: '購物袋', en: 'shopping bag', order: 4),
  CatalogTagData(id: 'obj_travel_passport', group: '物件', zh: '護照', en: 'passport', order: 4),
  CatalogTagData(id: 'obj_travel_boarding_pass', group: '物件', zh: '登機證', en: 'boarding pass', order: 4),
  CatalogTagData(id: 'obj_travel_guidebook', group: '物件', zh: '旅遊指南', en: 'travel guidebook', order: 4),
  CatalogTagData(id: 'obj_travel_train', group: '物件', zh: '火車', en: 'train', order: 4),
  CatalogTagData(id: 'obj_travel_bus', group: '物件', zh: '公車', en: 'bus', order: 4),
  CatalogTagData(id: 'obj_travel_taxi', group: '物件', zh: '計程車', en: 'taxi', order: 4),
  CatalogTagData(id: 'obj_travel_boat', group: '物件', zh: '小船', en: 'boat', order: 4),
  CatalogTagData(id: 'obj_travel_hot_air_balloon', group: '物件', zh: '熱氣球', en: 'hot air balloon', order: 4),

  // 日常／裝飾（11）
  CatalogTagData(id: 'obj_daily_potted_plant', group: '物件', zh: '盆栽', en: 'potted plant', order: 4),
  CatalogTagData(id: 'obj_daily_vase', group: '物件', zh: '花瓶', en: 'vase', order: 4),
  CatalogTagData(id: 'obj_daily_picture_frame', group: '物件', zh: '相框', en: 'picture frame', order: 4),
  CatalogTagData(id: 'obj_daily_wall_clock', group: '物件', zh: '掛鐘', en: 'wall clock', order: 4),
  CatalogTagData(id: 'obj_daily_alarm_clock', group: '物件', zh: '鬧鐘', en: 'alarm clock', order: 4),
  CatalogTagData(id: 'obj_daily_tissue_box', group: '物件', zh: '面紙盒', en: 'tissue box', order: 4),
  CatalogTagData(id: 'obj_daily_remote_control', group: '物件', zh: '遙控器', en: 'remote control', order: 4),
  CatalogTagData(id: 'obj_daily_flashlight', group: '物件', zh: '手電筒', en: 'flashlight', order: 4),
  CatalogTagData(id: 'obj_daily_broom', group: '物件', zh: '掃把', en: 'broom', order: 4),
  CatalogTagData(id: 'obj_daily_laundry_basket', group: '物件', zh: '洗衣籃', en: 'laundry basket', order: 4),
  CatalogTagData(id: 'obj_daily_kite', group: '物件', zh: '風箏', en: 'kite', order: 4),
];
