/// Built-in outfit references for users who want a complete, reusable starting
/// point instead of designing every garment dimension from scratch.
///
/// Garment nouns and the most important construction words intentionally use
/// the same English forms as the existing Danbooru-oriented clothing catalog.
/// Colors, materials and styling words remain separate here so the app can
/// resolve them back to ordinary selectable tags and compose one prompt phrase
/// per garment.
class OutfitPiecePresetData {
  const OutfitPiecePresetData({
    required this.scope,
    required this.garment,
    this.mainColor,
    this.secondaryColor,
    this.cut,
    this.fit,
    this.length,
    this.styles = const <String>[],
    this.materials = const <String>[],
    this.details = const <String>[],
    this.patterns = const <String>[],
  });

  final String scope;
  final String garment;
  final String? mainColor;
  final String? secondaryColor;
  final String? cut;
  final String? fit;
  final String? length;
  final List<String> styles;
  final List<String> materials;
  final List<String> details;
  final List<String> patterns;
}

class OutfitReferencePresetData {
  const OutfitReferencePresetData({
    required this.id,
    required this.category,
    required this.name,
    required this.palette,
    required this.description,
    required this.pieces,
    this.mainStyle,
    this.subStyle,
    this.mood,
    this.occasion,
  });

  final String id;
  final String category;
  final String name;
  final String palette;
  final String description;
  final List<OutfitPiecePresetData> pieces;
  final String? mainStyle;
  final String? subStyle;
  final String? mood;
  final String? occasion;

  String get combinationId => 'builtin_outfit_reference_$id';
}

const outfitReferencePresets = <OutfitReferencePresetData>[
  // 日常／學院 -------------------------------------------------------------
  OutfitReferencePresetData(
    id: 'romantic_summer_sundress',
    category: '日常／學院',
    name: '粉白蕾絲夏日洋裝',
    palette: '淺粉紅 × 白色',
    description: '輕盈棉質背心裙，以白色蕾絲和小花圖案增加清爽甜美感。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'sundress',
        mainColor: 'light pink',
        secondaryColor: 'white',
        fit: 'fitted',
        length: 'above knee',
        materials: ['cotton'],
        details: ['lace trim', 'bow'],
        patterns: ['floral pattern'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'sandals',
        mainColor: 'white',
        secondaryColor: 'light pink',
      ),
    ],
    mainStyle: 'feminine style',
    subStyle: 'romantic feminine style',
    mood: 'romantic mood',
    occasion: 'date outfit',
  ),
  OutfitReferencePresetData(
    id: 'navy_academy_uniform',
    category: '日常／學院',
    name: '海軍藍白學院制服',
    palette: '海軍藍 × 白色',
    description: '端正的學院制服，以白色滾邊、百褶與緞帶形成清楚層次。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'costume',
        garment: 'school uniform',
        mainColor: 'navy',
        secondaryColor: 'white',
        materials: ['cotton'],
        details: ['pleats', 'ribbon', 'piping'],
        patterns: ['solid color'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'loafers',
        mainColor: 'brown',
        secondaryColor: 'navy',
      ),
    ],
    mainStyle: 'preppy style',
    subStyle: 'classic elegant style',
    mood: 'innocent mood',
    occasion: 'school outfit',
  ),
  OutfitReferencePresetData(
    id: 'cream_cafe_knit',
    category: '日常／學院',
    name: '奶油咖啡針織套裝',
    palette: '奶油色 × 咖啡色 × 米色',
    description: '溫暖針織上衣搭配及膝 A 字裙，適合咖啡廳或秋季日常場景。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'knit top',
        mainColor: 'cream',
        secondaryColor: 'coffee',
        fit: 'regular fit',
        length: 'waist length',
        materials: ['knit'],
        details: ['buttons'],
        patterns: ['solid color'],
      ),
      OutfitPiecePresetData(
        scope: 'skirt',
        garment: 'a-line skirt',
        mainColor: 'beige',
        secondaryColor: 'coffee',
        cut: 'natural waist',
        fit: 'regular fit',
        length: 'knee length',
        materials: ['wool'],
        details: ['pleats'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'loafers',
        mainColor: 'brown',
        secondaryColor: 'cream',
      ),
    ],
    mainStyle: 'casual style',
    subStyle: 'smart casual style',
    mood: 'sweet mood',
    occasion: 'cafe outfit',
  ),
  OutfitReferencePresetData(
    id: 'sky_blue_pleated_school',
    category: '日常／學院',
    name: '白天藍清爽百褶穿搭',
    palette: '白色 × 天藍色',
    description: '白色女式襯衫搭天藍百褶裙，配短襪與瑪莉珍鞋，乾淨明亮。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'blouse',
        mainColor: 'white',
        secondaryColor: 'sky blue',
        cut: 'short sleeves',
        fit: 'fitted',
        length: 'waist length',
        materials: ['cotton'],
        details: ['bow'],
      ),
      OutfitPiecePresetData(
        scope: 'skirt',
        garment: 'pleated skirt',
        mainColor: 'sky blue',
        secondaryColor: 'white',
        cut: 'high-waisted',
        length: 'above knee',
        materials: ['cotton'],
        details: ['pleats'],
      ),
      OutfitPiecePresetData(
        scope: 'socks',
        garment: 'socks',
        mainColor: 'white',
        secondaryColor: 'sky blue',
        length: 'ankle length',
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'mary janes',
        mainColor: 'white',
        secondaryColor: 'sky blue',
      ),
    ],
    mainStyle: 'cute style',
    subStyle: 'sweet cute style',
    mood: 'innocent mood',
    occasion: 'school outfit',
  ),
  OutfitReferencePresetData(
    id: 'sage_shirt_dress',
    category: '日常／學院',
    name: '鼠尾草綠襯衫裙',
    palette: '鼠尾草綠 × 奶油色',
    description: '自然色調的及膝襯衫裙，以腰帶與鈕扣維持俐落輪廓。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'shirt dress',
        mainColor: 'sage green',
        secondaryColor: 'cream',
        fit: 'regular fit',
        length: 'knee length',
        materials: ['linen'],
        details: ['belt', 'buttons'],
        patterns: ['solid color'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'flats',
        mainColor: 'cream',
        secondaryColor: 'sage green',
      ),
    ],
    mainStyle: 'minimalist style',
    subStyle: 'relaxed casual style',
    mood: 'elegant mood',
    occasion: 'daily outfit',
  ),
  OutfitReferencePresetData(
    id: 'charcoal_office',
    category: '日常／學院',
    name: '象牙白炭灰辦公穿搭',
    palette: '象牙白 × 炭灰色 × 黑色',
    description: '絲質襯衫、鉛筆裙與西裝外套組成成熟但不過度正式的辦公造型。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'blouse',
        mainColor: 'ivory',
        secondaryColor: 'charcoal',
        cut: 'long sleeves',
        fit: 'fitted',
        materials: ['silk'],
      ),
      OutfitPiecePresetData(
        scope: 'skirt',
        garment: 'pencil skirt',
        mainColor: 'charcoal',
        secondaryColor: 'ivory',
        cut: 'high-waisted',
        fit: 'slim fit',
        length: 'knee length',
        materials: ['wool'],
      ),
      OutfitPiecePresetData(
        scope: 'outerwear',
        garment: 'blazer',
        mainColor: 'gray',
        secondaryColor: 'black',
        fit: 'regular fit',
        length: 'hip length',
        details: ['buttons'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'pumps',
        mainColor: 'black',
      ),
    ],
    mainStyle: 'elegant style',
    subStyle: 'smart casual style',
    mood: 'mature mood',
    occasion: 'office outfit',
  ),

  // 優雅／正式 -------------------------------------------------------------
  OutfitReferencePresetData(
    id: 'victorian_gothic_gown',
    category: '優雅／正式',
    name: '黑紅維多利亞哥德晚禮服',
    palette: '黑色 × 深紅色',
    description: '黑色天鵝絨長禮服以深紅蕾絲、荷葉邊與玫瑰圖案營造華麗哥德感。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'evening gown',
        mainColor: 'black',
        secondaryColor: 'dark red',
        fit: 'fitted',
        length: 'floor length',
        materials: ['velvet', 'lace'],
        details: ['lace trim', 'frills', 'ruffles'],
        patterns: ['rose pattern'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'platform heels',
        mainColor: 'black',
        secondaryColor: 'dark red',
      ),
    ],
    mainStyle: 'gothic style',
    subStyle: 'Victorian gothic style',
    mood: 'dark mood',
    occasion: 'formal event outfit',
  ),
  OutfitReferencePresetData(
    id: 'midnight_starlight_ball_gown',
    category: '優雅／正式',
    name: '午夜藍銀色星光舞會禮服',
    palette: '午夜藍 × 銀色',
    description: '午夜藍緞面舞會禮服，以銀色亮片和星形圖案呈現夜空層次。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'ball gown',
        mainColor: 'midnight blue',
        secondaryColor: 'silver',
        fit: 'fitted',
        length: 'floor length',
        materials: ['satin', 'organza'],
        details: ['sequins'],
        patterns: ['star pattern'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'stiletto heels',
        mainColor: 'silver',
        secondaryColor: 'navy',
      ),
    ],
    mainStyle: 'elegant style',
    subStyle: 'classic elegant style',
    mood: 'luxurious mood',
    occasion: 'formal event outfit',
  ),
  OutfitReferencePresetData(
    id: 'burgundy_cocktail_dress',
    category: '優雅／正式',
    name: '酒紅金邊雞尾酒洋裝',
    palette: '酒紅色 × 金色',
    description: '修身酒紅緞面洋裝，以金色抓皺與腰帶細節呈現派對質感。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'cocktail dress',
        mainColor: 'burgundy',
        secondaryColor: 'gold',
        cut: 'one-shoulder',
        fit: 'slim fit',
        length: 'knee length',
        materials: ['satin'],
        details: ['ruched', 'belt'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'pumps',
        mainColor: 'black',
        secondaryColor: 'gold',
      ),
    ],
    mainStyle: 'elegant style',
    subStyle: 'glamorous sexy style',
    mood: 'mature mood',
    occasion: 'party outfit',
  ),
  OutfitReferencePresetData(
    id: 'ivory_rose_gold_guest_dress',
    category: '優雅／正式',
    name: '象牙白玫瑰金婚宴洋裝',
    palette: '象牙白 × 玫瑰金',
    description: '象牙白雪紡中長洋裝，搭配玫瑰金花卉刺繡，適合婚宴賓客服裝。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'dress',
        mainColor: 'ivory',
        secondaryColor: 'rose gold',
        cut: 'one-shoulder',
        fit: 'regular fit',
        length: 'midi',
        materials: ['chiffon'],
        details: ['floral embroidery'],
        patterns: ['floral pattern'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'ankle strap heels',
        mainColor: 'ivory',
        secondaryColor: 'rose gold',
      ),
    ],
    mainStyle: 'feminine style',
    subStyle: 'classic elegant style',
    mood: 'romantic mood',
    occasion: 'wedding guest outfit',
  ),
  OutfitReferencePresetData(
    id: 'emerald_slit_gown',
    category: '優雅／正式',
    name: '翡翠綠黑邊開衩晚禮服',
    palette: '翡翠綠 × 黑色',
    description: '翡翠綠絲質修身禮服，以黑色高開衩邊線拉長整體比例。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'evening gown',
        mainColor: 'emerald green',
        secondaryColor: 'black',
        fit: 'fitted',
        length: 'floor length',
        materials: ['silk'],
        details: ['high slit', 'draped'],
        patterns: ['solid color'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'stiletto heels',
        mainColor: 'black',
        secondaryColor: 'emerald green',
      ),
    ],
    mainStyle: 'elegant style',
    subStyle: 'glamorous sexy style',
    mood: 'luxurious mood',
    occasion: 'formal event outfit',
  ),
  OutfitReferencePresetData(
    id: 'lavender_princess_gown',
    category: '優雅／正式',
    name: '薰衣草銀邊公主舞會禮服',
    palette: '薰衣草紫 × 銀色',
    description: '歐根紗與薄紗堆疊的公主禮服，加入銀色珍珠與荷葉邊。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'ball gown',
        mainColor: 'lavender',
        secondaryColor: 'silver',
        cut: 'off-shoulder',
        fit: 'fitted',
        length: 'floor length',
        materials: ['organza', 'tulle'],
        details: ['ruffles', 'pearls'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'high heels',
        mainColor: 'silver',
        secondaryColor: 'lavender',
      ),
    ],
    mainStyle: 'fantasy style',
    subStyle: 'princess fantasy style',
    mood: 'luxurious mood',
    occasion: 'formal event outfit',
  ),

  // 甜美／浪漫 -------------------------------------------------------------
  OutfitReferencePresetData(
    id: 'pink_blue_maid',
    category: '甜美／浪漫',
    name: '粉藍蝴蝶結女僕裝',
    palette: '粉紅色 × 嬰兒藍',
    description: '粉色女僕裝以嬰兒藍蝴蝶結、褶邊和蕾絲增加糖果般的層次。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'costume',
        garment: 'maid outfit',
        mainColor: 'pink',
        secondaryColor: 'baby blue',
        materials: ['cotton', 'lace'],
        details: ['bow', 'frills', 'lace trim'],
        patterns: ['two-tone'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'mary janes',
        mainColor: 'baby blue',
        secondaryColor: 'pink',
      ),
    ],
    mainStyle: 'cute style',
    subStyle: 'sweet cute style',
    mood: 'playful mood',
    occasion: 'cafe outfit',
  ),
  OutfitReferencePresetData(
    id: 'sakura_yukata',
    category: '甜美／浪漫',
    name: '白粉櫻花浴衣',
    palette: '白色 × 粉紅色',
    description: '白色浴衣配粉色腰帶與櫻花圖案，保留輕柔的日式夏祭氣氛。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'costume',
        garment: 'yukata',
        mainColor: 'white',
        secondaryColor: 'pink',
        materials: ['cotton'],
        details: ['belt', 'ribbon'],
        patterns: ['cherry blossom pattern'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'zori',
        mainColor: 'brown',
        secondaryColor: 'pink',
      ),
    ],
    mainStyle: 'feminine style',
    subStyle: 'romantic feminine style',
    mood: 'sweet mood',
    occasion: 'casual outing outfit',
  ),
  OutfitReferencePresetData(
    id: 'lilac_ruffle_dress',
    category: '甜美／浪漫',
    name: '淡紫奶油荷葉邊洋裝',
    palette: '淡紫色 × 奶油色',
    description: '淡紫雪紡短洋裝加上奶油色荷葉邊，柔和且不會過度繁複。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'one-piece dress',
        mainColor: 'lilac',
        secondaryColor: 'cream',
        fit: 'regular fit',
        length: 'above knee',
        materials: ['chiffon'],
        details: ['ruffles', 'bow'],
        patterns: ['solid color'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'ankle boots',
        mainColor: 'cream',
        secondaryColor: 'lilac',
      ),
    ],
    mainStyle: 'cute style',
    subStyle: 'sweet cute style',
    mood: 'sweet mood',
    occasion: 'date outfit',
  ),
  OutfitReferencePresetData(
    id: 'mint_slip_dress',
    category: '甜美／浪漫',
    name: '薄荷綠白邊吊帶洋裝',
    palette: '薄荷綠 × 白色',
    description: '薄荷綠緞面吊帶洋裝配白色蕾絲，呈現清爽而細緻的約會造型。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'slip dress',
        mainColor: 'mint green',
        secondaryColor: 'white',
        fit: 'fitted',
        length: 'midi',
        materials: ['satin'],
        details: ['lace trim'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'strappy sandals',
        mainColor: 'white',
        secondaryColor: 'mint green',
      ),
    ],
    mainStyle: 'feminine style',
    subStyle: 'romantic feminine style',
    mood: 'romantic mood',
    occasion: 'date outfit',
  ),
  OutfitReferencePresetData(
    id: 'peach_tiered_set',
    category: '甜美／浪漫',
    name: '蜜桃象牙白蛋糕裙穿搭',
    palette: '蜜桃色 × 象牙白',
    description: '象牙白泡泡袖襯衫搭蜜桃色分層裙，以蝴蝶結和荷葉邊連結上下身。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'blouse',
        mainColor: 'ivory',
        secondaryColor: 'peach',
        cut: 'puff sleeves',
        fit: 'fitted',
        materials: ['cotton'],
        details: ['bow'],
      ),
      OutfitPiecePresetData(
        scope: 'skirt',
        garment: 'tiered skirt',
        mainColor: 'peach',
        secondaryColor: 'ivory',
        cut: 'high-waisted',
        length: 'midi',
        materials: ['chiffon'],
        details: ['ruffles', 'layered'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'mary janes',
        mainColor: 'ivory',
        secondaryColor: 'peach',
      ),
    ],
    mainStyle: 'cute style',
    subStyle: 'romantic feminine style',
    mood: 'sweet mood',
    occasion: 'cafe outfit',
  ),
  OutfitReferencePresetData(
    id: 'aqua_sailor_uniform',
    category: '甜美／浪漫',
    name: '水藍白邊水手服',
    palette: '水藍色 × 白色',
    description: '水藍水手服以白色百褶、緞帶與條紋整理成明亮活潑的校園造型。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'costume',
        garment: 'sailor uniform',
        mainColor: 'aqua',
        secondaryColor: 'white',
        materials: ['cotton'],
        details: ['pleats', 'ribbon'],
        patterns: ['striped'],
      ),
      OutfitPiecePresetData(
        scope: 'socks',
        garment: 'socks',
        mainColor: 'white',
        secondaryColor: 'aqua',
        length: 'crew length',
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'loafers',
        mainColor: 'white',
        secondaryColor: 'aqua',
      ),
    ],
    mainStyle: 'preppy style',
    subStyle: 'sweet cute style',
    mood: 'playful mood',
    occasion: 'school outfit',
  ),

  // 街頭／運動 -------------------------------------------------------------
  OutfitReferencePresetData(
    id: 'purple_cyber_techwear',
    category: '街頭／運動',
    name: '黑紫賽博龐克機能穿搭',
    palette: '黑色 × 紫色',
    description: '短版上衣、工裝褲與戰鬥靴以網眼、綁帶和鏈條建立機能層次。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'crop top',
        mainColor: 'black',
        secondaryColor: 'purple',
        cut: 'sleeveless',
        fit: 'fitted',
        length: 'cropped',
        materials: ['mesh'],
        details: ['straps', 'cutout'],
      ),
      OutfitPiecePresetData(
        scope: 'pants',
        garment: 'cargo pants',
        mainColor: 'black',
        secondaryColor: 'purple',
        fit: 'loose fit',
        length: 'full length',
        materials: ['leather'],
        details: ['straps', 'chains'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'combat boots',
        mainColor: 'black',
        secondaryColor: 'purple',
        details: ['buckles'],
      ),
    ],
    mainStyle: 'futuristic style',
    subStyle: 'cyberpunk style',
    mood: 'cool mood',
    occasion: 'casual outing outfit',
  ),
  OutfitReferencePresetData(
    id: 'pink_basketball_set',
    category: '街頭／運動',
    name: '白粉籃球運動穿搭',
    palette: '白色 × 粉紅色',
    description: '白色籃球球衣搭粉色運動短褲與球鞋，使用網眼和撞色滾邊。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'basketball jersey',
        mainColor: 'white',
        secondaryColor: 'pink',
        cut: 'sleeveless',
        fit: 'loose fit',
        length: 'hip length',
        materials: ['mesh'],
        patterns: ['color block'],
      ),
      OutfitPiecePresetData(
        scope: 'shorts',
        garment: 'sports shorts',
        mainColor: 'pink',
        secondaryColor: 'white',
        fit: 'regular fit',
        length: 'short length',
        materials: ['mesh'],
        patterns: ['striped'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'basketball shoes',
        mainColor: 'white',
        secondaryColor: 'pink',
      ),
    ],
    mainStyle: 'sporty style',
    subStyle: 'athleisure style',
    mood: 'sporty mood',
    occasion: 'sports outfit',
  ),
  OutfitReferencePresetData(
    id: 'navy_red_tracksuit',
    category: '街頭／運動',
    name: '海軍藍紅邊運動套裝',
    palette: '海軍藍 × 紅色 × 白色',
    description: '海軍藍運動外套與長褲以紅色邊線統一，再用白紅跑鞋提亮。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'outerwear',
        garment: 'track jacket',
        mainColor: 'navy',
        secondaryColor: 'red',
        fit: 'regular fit',
        length: 'hip length',
        materials: ['cotton'],
        details: ['zipper'],
        patterns: ['striped'],
      ),
      OutfitPiecePresetData(
        scope: 'pants',
        garment: 'sweatpants',
        mainColor: 'navy',
        secondaryColor: 'red',
        fit: 'relaxed fit',
        length: 'full length',
        materials: ['cotton'],
        patterns: ['striped'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'running shoes',
        mainColor: 'white',
        secondaryColor: 'red',
      ),
    ],
    mainStyle: 'sporty style',
    subStyle: 'athleisure style',
    mood: 'sporty mood',
    occasion: 'gym outfit',
  ),
  OutfitReferencePresetData(
    id: 'gray_orange_streetwear',
    category: '街頭／運動',
    name: '灰橘街頭連帽穿搭',
    palette: '灰色 × 橘色 × 黑色',
    description: '灰色寬鬆連帽上衣搭黑色工裝褲，以橘色滾邊增加街頭辨識度。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'hoodie',
        mainColor: 'light gray',
        secondaryColor: 'orange',
        fit: 'oversized',
        length: 'hip length',
        materials: ['cotton'],
        details: ['zipper'],
      ),
      OutfitPiecePresetData(
        scope: 'pants',
        garment: 'cargo pants',
        mainColor: 'black',
        secondaryColor: 'orange',
        fit: 'loose fit',
        length: 'full length',
        materials: ['cotton'],
        details: ['straps'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'sneakers',
        mainColor: 'gray',
        secondaryColor: 'orange',
      ),
    ],
    mainStyle: 'streetwear style',
    subStyle: 'urban streetwear style',
    mood: 'cool mood',
    occasion: 'casual outing outfit',
  ),
  OutfitReferencePresetData(
    id: 'denim_y2k',
    category: '街頭／運動',
    name: '丹寧白色 Y2K 穿搭',
    palette: '白色 × 藍色',
    description: '白色短版上衣搭丹寧短褲與短版牛仔外套，保留輕快復古比例。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'crop top',
        mainColor: 'white',
        secondaryColor: 'baby blue',
        cut: 'short sleeves',
        fit: 'fitted',
        length: 'cropped',
        materials: ['cotton'],
      ),
      OutfitPiecePresetData(
        scope: 'shorts',
        garment: 'denim shorts',
        mainColor: 'blue',
        secondaryColor: 'white',
        cut: 'high-waisted',
        fit: 'slim fit',
        length: 'short length',
        materials: ['denim'],
      ),
      OutfitPiecePresetData(
        scope: 'outerwear',
        garment: 'denim jacket',
        mainColor: 'blue',
        secondaryColor: 'white',
        fit: 'regular fit',
        length: 'cropped',
        materials: ['denim'],
        details: ['buttons'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'sneakers',
        mainColor: 'white',
        secondaryColor: 'blue',
      ),
    ],
    mainStyle: 'streetwear style',
    subStyle: 'Y2K style',
    mood: 'playful mood',
    occasion: 'casual outing outfit',
  ),
  OutfitReferencePresetData(
    id: 'black_red_punk_leather',
    category: '街頭／運動',
    name: '黑紅龐克皮革穿搭',
    palette: '黑色 × 紅色',
    description: '皮革馬甲、皮褲、短版皮夾克和厚底靴，以紅色繫帶與鏈條貫穿全身。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'corset top',
        mainColor: 'black',
        secondaryColor: 'red',
        fit: 'fitted',
        materials: ['leather'],
        details: ['lace-up'],
      ),
      OutfitPiecePresetData(
        scope: 'pants',
        garment: 'leather pants',
        mainColor: 'black',
        secondaryColor: 'red',
        fit: 'slim fit',
        length: 'full length',
        materials: ['leather'],
        details: ['zipper', 'chains'],
      ),
      OutfitPiecePresetData(
        scope: 'outerwear',
        garment: 'leather jacket',
        mainColor: 'black',
        secondaryColor: 'red',
        fit: 'fitted',
        length: 'cropped',
        materials: ['leather'],
        details: ['zipper'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'platform boots',
        mainColor: 'black',
        secondaryColor: 'red',
        details: ['buckles'],
      ),
    ],
    mainStyle: 'punk style',
    subStyle: 'urban streetwear style',
    mood: 'tough mood',
    occasion: 'party outfit',
  ),

  // 奇幻／特色 -------------------------------------------------------------
  OutfitReferencePresetData(
    id: 'purple_witch_dress',
    category: '奇幻／特色',
    name: '黑紫星紋女巫洋裝',
    palette: '黑色 × 紫色',
    description: '黑色天鵝絨長洋裝加入紫色蕾絲與星形圖案，適合作為女巫造型基底。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'dress',
        mainColor: 'black',
        secondaryColor: 'purple',
        fit: 'fitted',
        length: 'maxi',
        materials: ['velvet'],
        details: ['lace trim', 'ruffles'],
        patterns: ['star pattern'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'ankle boots',
        mainColor: 'black',
        secondaryColor: 'purple',
      ),
    ],
    mainStyle: 'fantasy style',
    subStyle: 'witch fantasy style',
    mood: 'mysterious mood',
    occasion: 'party outfit',
  ),
  OutfitReferencePresetData(
    id: 'midnight_ninja',
    category: '奇幻／特色',
    name: '深藍銀邊女忍者套裝',
    palette: '午夜藍 × 銀色 × 黑色',
    description: '午夜藍忍者套裝以銀色綁帶和網眼材質增加層次，搭配黑色分趾靴。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'costume',
        garment: 'ninja outfit',
        mainColor: 'midnight blue',
        secondaryColor: 'silver',
        materials: ['cotton', 'mesh'],
        details: ['straps', 'belt'],
        patterns: ['two-tone'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'tabi boots',
        mainColor: 'black',
        secondaryColor: 'midnight blue',
      ),
    ],
    mainStyle: 'fantasy style',
    subStyle: 'techwear style',
    mood: 'tough mood',
    occasion: 'outdoor outfit',
  ),
  OutfitReferencePresetData(
    id: 'burgundy_steampunk',
    category: '奇幻／特色',
    name: '酒紅黑蒸汽龐克連身裝',
    palette: '酒紅色 × 黑色 × 棕色',
    description: '酒紅連身褲搭黑色皮革、扣環與鏈條，再以棕色踝靴完成蒸汽龐克輪廓。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'onepiece',
        garment: 'jumpsuit',
        mainColor: 'burgundy',
        secondaryColor: 'black',
        fit: 'fitted',
        materials: ['leather'],
        details: ['buckles', 'chains', 'belt'],
        patterns: ['color block'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'ankle boots',
        mainColor: 'brown',
        secondaryColor: 'burgundy',
        details: ['buckles'],
      ),
    ],
    mainStyle: 'vintage style',
    subStyle: 'steampunk style',
    mood: 'mysterious mood',
    occasion: 'party outfit',
  ),
  OutfitReferencePresetData(
    id: 'black_gold_gothic_maid',
    category: '奇幻／特色',
    name: '黑金哥德女僕裝',
    palette: '黑色 × 金色',
    description: '黑色女僕裝以金色蕾絲、褶邊與蝴蝶結強化華麗哥德氣氛。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'costume',
        garment: 'maid outfit',
        mainColor: 'black',
        secondaryColor: 'gold',
        materials: ['velvet', 'lace'],
        details: ['lace trim', 'frills', 'bow'],
        patterns: ['solid color'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'platform shoes',
        mainColor: 'black',
        secondaryColor: 'gold',
      ),
    ],
    mainStyle: 'gothic style',
    subStyle: 'romantic gothic style',
    mood: 'luxurious mood',
    occasion: 'party outfit',
  ),
  OutfitReferencePresetData(
    id: 'white_navy_kyudo',
    category: '奇幻／特色',
    name: '白海軍藍弓道服',
    palette: '白色 × 海軍藍 × 棕色',
    description: '白色弓道服搭海軍藍百褶與腰帶，配分趾襪及棕色草履。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'costume',
        garment: 'kyudo uniform',
        mainColor: 'white',
        secondaryColor: 'navy',
        materials: ['cotton'],
        details: ['pleats', 'belt'],
        patterns: ['solid color'],
      ),
      OutfitPiecePresetData(
        scope: 'socks',
        garment: 'socks',
        mainColor: 'white',
        secondaryColor: 'navy',
        styles: ['tabi socks'],
        length: 'ankle length',
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'zori',
        mainColor: 'brown',
        secondaryColor: 'navy',
      ),
    ],
    mainStyle: 'elegant style',
    subStyle: 'classic elegant style',
    mood: 'formal mood',
    occasion: 'sports outfit',
  ),
  OutfitReferencePresetData(
    id: 'ivory_rose_gold_wedding',
    category: '奇幻／特色',
    name: '象牙白玫瑰金婚紗',
    palette: '象牙白 × 玫瑰金',
    description: '象牙白婚紗以玫瑰金刺繡、珍珠和蕾絲收邊，作為正式婚禮造型。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'costume',
        garment: 'wedding dress',
        mainColor: 'ivory',
        secondaryColor: 'rose gold',
        materials: ['satin', 'tulle'],
        details: ['lace trim', 'floral embroidery', 'pearls'],
        patterns: ['floral pattern'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'pumps',
        mainColor: 'ivory',
        secondaryColor: 'rose gold',
      ),
    ],
    mainStyle: 'elegant style',
    subStyle: 'princess fantasy style',
    mood: 'romantic mood',
    occasion: 'formal event outfit',
  ),
];
