import 'outfit_reference_data.dart';

/// Pink-and-white outfit references kept separately so their palette can grow
/// without mixing them into the blue-only inspiration catalog.
const pinkOutfitReferencePresets = <OutfitReferencePresetData>[
  OutfitReferencePresetData(
    id: 'pink_cat_lace_off_shoulder',
    category: '甜美／浪漫',
    name: '粉白貓系蕾絲露肩套裝',
    palette: '白色 × 粉紅色 × 黑色',
    description: '白色露肩束腰上衣配粉紅花邊，搭黑色荷葉迷你裙、粉白蕾絲胸罩與長襪；粉紅貓耳、貓尾以角色獸人特徵加入，不使用裝飾品。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'blouse',
        mainColor: 'white',
        secondaryColor: 'pink',
        detailColor: 'pink',
        cut: 'off-shoulder',
        fit: 'fitted',
        length: 'waist length',
        materials: ['cotton'],
        details: ['corset lacing', 'lace trim', 'frills', 'ribbon'],
      ),
      OutfitPiecePresetData(
        scope: 'skirt',
        garment: 'tiered skirt',
        mainColor: 'black',
        secondaryColor: 'pink',
        detailColor: 'white',
        cut: 'high-waisted',
        fit: 'fitted',
        length: 'mini',
        materials: ['chiffon'],
        details: ['lace trim', 'frills', 'ruffles'],
      ),
      OutfitPiecePresetData(
        scope: 'bra',
        garment: 'lace bra',
        mainColor: 'white',
        secondaryColor: 'pink',
      ),
      OutfitPiecePresetData(
        scope: 'socks',
        garment: 'thighhighs',
        mainColor: 'white',
        secondaryColor: 'pink',
        materials: ['lace'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'platform shoes',
        mainColor: 'white',
        secondaryColor: 'pink',
      ),
    ],
    mainStyle: 'feminine',
    subStyle: 'sweet feminine style',
    mood: 'sweet mood',
    featureTags: [
      'cat ears',
      'pink animal ears',
      'cat tail',
      'pink animal tail',
    ],
  ),
  OutfitReferencePresetData(
    id: 'pink_white_equestrian_layered',
    category: '甜美／浪漫',
    name: '粉白馬術風分層裙裝',
    palette: '粉紅色 × 白色 × 淺粉紅',
    description: '白色長袖鈕扣襯衫配粉紅領結與腰帶，下身為粉白分層蕾絲裙和馬術靴；保留騎馬服的俐落腰線，同時維持甜美層次。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'accessory',
        garment: 'large hair bow',
        mainColor: 'pink',
        secondaryColor: 'white',
      ),
      OutfitPiecePresetData(
        scope: 'accessory',
        garment: 'neck ribbon',
        mainColor: 'hot pink',
        secondaryColor: 'white',
      ),
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'button-up shirt',
        mainColor: 'white',
        secondaryColor: 'light pink',
        detailColor: 'light pink',
        cut: 'long sleeves',
        fit: 'fitted',
        length: 'waist length',
        materials: ['cotton'],
        details: ['buttons', 'lace trim', 'ruffles'],
        patterns: ['solid color'],
      ),
      OutfitPiecePresetData(
        scope: 'accessory',
        garment: 'belt',
        mainColor: 'hot pink',
        secondaryColor: 'white',
      ),
      OutfitPiecePresetData(
        scope: 'skirt',
        garment: 'tiered skirt',
        mainColor: 'pink',
        secondaryColor: 'white',
        detailColor: 'white',
        cut: 'high-waisted',
        fit: 'regular fit',
        length: 'midi',
        materials: ['chiffon'],
        details: ['layered', 'lace trim', 'ruffles', 'ribbon'],
        patterns: ['solid color'],
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'riding boots',
        mainColor: 'white',
        secondaryColor: 'pink',
        materials: ['leather'],
        details: ['lace-up'],
      ),
    ],
    mainStyle: 'feminine',
    subStyle: 'romantic feminine style',
    mood: 'sweet mood',
    occasion: 'outdoor outfit',
  ),
  OutfitReferencePresetData(
    id: 'lala_wolf_white_pink_cropped_hoodie',
    category: '甜美／浪漫',
    name: '白粉狼耳短版連帽套裝',
    palette: '白色 × 粉紅色 × 淺粉紅',
    description:
        '白粉無袖短版連帽上衣搭配安全短褲、粉白百褶分層短裙、踝襪與運動鞋；附心形拉鍊拉環、胸前小愛心徽章與可編輯的白色大型蓬鬆狼尾。',
    pieces: [
      OutfitPiecePresetData(
        scope: 'top',
        garment: 'cropped hoodie',
        mainColor: 'white',
        secondaryColor: 'pink',
        cut: 'sleeveless',
        fit: 'fitted',
        materials: ['cotton'],
        details: [
          'zipper',
          'heart-shaped zipper pull',
          'heart emblem on chest'
        ],
        patterns: ['heart pattern'],
      ),
      OutfitPiecePresetData(
        scope: 'shorts',
        garment: 'safety shorts',
        mainColor: 'white',
        secondaryColor: 'pink',
        fit: 'fitted',
        length: 'micro length',
        materials: ['cotton'],
      ),
      OutfitPiecePresetData(
        scope: 'skirt',
        garment: 'pleated skirt',
        mainColor: 'pink',
        secondaryColor: 'white',
        detailColor: 'light pink',
        cut: 'high-waisted',
        fit: 'fitted',
        length: 'mini',
        materials: ['cotton'],
        details: ['layered', 'frills', 'pleats'],
        patterns: ['gradient'],
      ),
      OutfitPiecePresetData(
        scope: 'socks',
        garment: 'ankle socks',
        mainColor: 'white',
        secondaryColor: 'pink',
      ),
      OutfitPiecePresetData(
        scope: 'shoes',
        garment: 'sneakers',
        mainColor: 'white',
        secondaryColor: 'pink',
      ),
    ],
    mainStyle: 'feminine',
    subStyle: 'sweet feminine style',
    mood: 'sweet mood',
    featureTags: [
      'wolf ears',
      'white animal ears',
      'large fluffy wolf tail',
      'white animal tail',
      'soft pink fur accents',
    ],
  ),
];
